{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNYAexSbOpEAIsb9L3N41qx",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/hmg8906/CienciaDatosCN/blob/TFM/deforest_master.R\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "WvTuEnQTG9i0"
      },
      "outputs": [],
      "source": [
        "# ============================================================\n",
        "# deforest_master.R  —  Pipeline completo (Steps 1–6)\n",
        "# Autor: tú :)\n",
        "# Descripción:\n",
        "#   (1) Reclasificación MapBiomas → bosque binario (1/0)\n",
        "#   (2) Distancia a borde bosque–no bosque (m)\n",
        "#   (3) Máscaras de transición (deforestación 1→0; bosque estable 1→1)\n",
        "#   (4) Muestreo supervisado desde transiciones + estáticos\n",
        "#   (5) XGBoost: entrenamiento, validación, prueba y exportes\n",
        "#   (6) Inferencia a rejilla (probabilidad y binario; acumulada a 2040)\n",
        "# Convenciones:\n",
        "#   1 = bosque, 0 = no-bosque; NA = sin dato\n",
        "# ============================================================\n",
        "\n",
        "suppressPackageStartupMessages({\n",
        "  need <- c(\"terra\",\"rnaturalearth\",\"data.table\",\"dplyr\",\"xgboost\",\"pROC\",\"PRROC\")\n",
        "  miss <- setdiff(need, rownames(installed.packages()))\n",
        "  if (length(miss)) install.packages(miss, dependencies = TRUE)\n",
        "  lapply(need, require, character.only = TRUE)\n",
        "})\n",
        "\n",
        "# ---------------- PARAMS (EDITA AQUÍ) ----------------\n",
        "root        <- \"C:/Users/henry.garcia/Desktop/Primates/predictors/DefRisk\"\n",
        "in_dir_mb   <- \"C:/Users/henry.garcia/Desktop/Primates/mapbiomas\"   # classification_YYYY.tif\n",
        "crs_metric  <- \"EPSG:6933\"    # CRS métrico para distancias si el input está en lon/lat\n",
        "\n",
        "# Ventanas de transición (train/valid/test)\n",
        "win_train   <- list(c(2000,2005), c(2005,2010), c(2010,2015))\n",
        "win_valid   <- c(2015,2020)\n",
        "win_test    <- c(2020,2023)\n",
        "\n",
        "# Tamaños de muestra por clase (por ventana)\n",
        "npos <- 15000; nneg <- 15000\n",
        "\n",
        "# Rásteres estáticos para muestreo (STEP 4)\n",
        "dir_static  <- file.path(root, \"rasters\", \"static\")\n",
        "static_paths <- file.path(dir_static, c(\n",
        "  \"elev.tif\",\"slope.tif\",\"dist_runap_crsfix.tif\",\n",
        "  \"dist_road_crsfix.tif\",\"dist_river_crsfix.tif\",\"dist_town_crsfix.tif\",\n",
        "  \"soil_C.tif\"\n",
        "))\n",
        "stopifnot(all(file.exists(static_paths)))\n",
        "\n",
        "# Inferencia (STEP 6)\n",
        "base_year       <- 2023\n",
        "res_tag         <- \"90m\"\n",
        "window_years    <- 3      # p.ej., 3 años si valid/test fueron 2020–2023\n",
        "target_year_cum <- 2040   # acumulada hasta 2040 (opcional)\n",
        "# Capas de inferencia — NOMBRES deben coincidir con las features del modelo\n",
        "paths_infer <- c(\n",
        "  elev              = file.path(root, \"rasters/static_90m/elev_90m.tif\"),\n",
        "  slope             = file.path(root, \"rasters/static_90m/slope_90m.tif\"),\n",
        "  dist_runap_crsfix = file.path(root, \"rasters/static_90m/dist_runap_crsfix_90m.tif\"),\n",
        "  dist_road_crsfix  = file.path(root, \"rasters/static_90m/dist_road_crsfix_90m.tif\"),\n",
        "  dist_river_crsfix = file.path(root, \"rasters/static_90m/dist_river_crsfix_90m.tif\"),\n",
        "  dist_town_crsfix  = file.path(root, \"rasters/static_90m/dist_town_crsfix_90m.tif\"),\n",
        "  soil_C            = file.path(root, \"rasters/static_90m/soil_C_90m.tif\"),\n",
        "  dist_edge         = file.path(root, sprintf(\"rasters/dist_edge_90m/dist_edge_%d_90m.tif\", base_year))\n",
        ")\n",
        "stopifnot(all(file.exists(paths_infer)))\n",
        "forest_mask_file <- file.path(root, \"rasters\", \"forest01\", sprintf(\"forest01_%d_%s.tif\", base_year, res_tag))\n",
        "use_forest_mask  <- file.exists(forest_mask_file)\n",
        "\n",
        "# Control de ejecución\n",
        "RUN_STEP1_RECLASS  <- TRUE\n",
        "RUN_STEP2_DISTEDGE <- TRUE\n",
        "RUN_STEP3_TRANS    <- TRUE\n",
        "RUN_STEP4_SAMPLE   <- TRUE\n",
        "RUN_STEP5_XGB      <- TRUE\n",
        "RUN_STEP6_INFER    <- TRUE\n",
        "# -----------------------------------------------------\n",
        "\n",
        "# ===== Opciones IO / rendimiento\n",
        "Sys.setenv(GDAL_CACHEMAX = \"1024\")\n",
        "terraOptions(todisk = TRUE, memfrac = 0.7, progress = 2)\n",
        "# terraOptions(tmpdir = \"D:/terra_tmp\")  # opcional (SSD)\n",
        "\n",
        "# ===== Carpetas de trabajo\n",
        "dir_forest    <- file.path(root, \"rasters\", \"forest01\")\n",
        "dir_distedge  <- file.path(root, \"rasters\", \"dist_edge\")\n",
        "dir_trans     <- file.path(root, \"rasters\", \"transitions\")\n",
        "dir_samples   <- file.path(root, \"samples\")\n",
        "dir_models    <- file.path(root, \"models\")\n",
        "dir_riskmaps  <- file.path(root, \"risk_maps\")\n",
        "for (d in c(dir_forest, dir_distedge, dir_trans, dir_samples, dir_models, dir_riskmaps)) {\n",
        "  dir.create(d, showWarnings = FALSE, recursive = TRUE)\n",
        "}\n",
        "\n",
        "log <- function(...) cat(sprintf(\"[%s] %s\\n\", format(Sys.time(), \"%H:%M:%S\"), paste0(..., collapse=\" \")))\n",
        "write_tif <- function(x, path, wopt=list(), overwrite=TRUE){\n",
        "  writeRaster(x, path, overwrite=overwrite,\n",
        "              wopt = modifyList(list(gdal = c(\"COMPRESS=LZW\",\"TILED=YES\",\"BIGTIFF=IF_SAFER\")), wopt))\n",
        "}\n",
        "\n",
        "# ============================================================\n",
        "# STEP 1 — Reclasificación MapBiomas → bosque binario (1/0)\n",
        "# ============================================================\n",
        "if (RUN_STEP1_RECLASS) {\n",
        "  log(\"STEP 1: Reclasificación MapBiomas → bosque 1/0\")\n",
        "  # AOI Colombia\n",
        "  co <- rnaturalearth::ne_countries(country = \"Colombia\", scale = \"medium\", returnclass = \"sf\") |> terra::vect()\n",
        "  # Buscar archivos\n",
        "  fs  <- list.files(in_dir_mb, pattern = \"classification_\\\\d{4}\\\\.tif$\", full.names = TRUE)\n",
        "  stopifnot(\"No se encontraron classification_YYYY.tif\" = length(fs) > 0)\n",
        "  yrs <- as.integer(gsub(\".*classification_(\\\\d{4})\\\\.tif$\", \"\\\\1\", fs))\n",
        "  ord <- order(yrs); fs <- fs[ord]; yrs <- yrs[ord]\n",
        "\n",
        "  reclass_to_forest01 <- function(r) {\n",
        "    r1 <- ifel((r == 0) | (r == 27), NA, r)                           # 0/27 → NA\n",
        "    r2 <- ifel((r1 == 3) | (r1 == 5) | (r1 == 6) | (r1 == 49), 1, r1) # bosque → 1\n",
        "    ifel(is.na(r2), NA, ifel(r2 == 1, 1, 0))                          # resto → 0\n",
        "  }\n",
        "\n",
        "  summary_list <- vector(\"list\", length(fs))\n",
        "  for (i in seq_along(fs)) {\n",
        "    log(sprintf(\"[%d/%d] %s\", i, length(fs), basename(fs[i])))\n",
        "    r <- rast(fs[i])\n",
        "    co_proj <- project(co, crs(r))\n",
        "    r_crop  <- crop(r, co_proj, snap = \"out\")\n",
        "    r_mask  <- mask(r_crop, co_proj)\n",
        "    rb <- reclass_to_forest01(r_mask)\n",
        "    out_i <- file.path(dir_forest, sprintf(\"forest01_%d.tif\", yrs[i]))\n",
        "    write_tif(rb, out_i, wopt=list(datatype=\"INT1U\", NAflag=255))\n",
        "    # resumen\n",
        "    n_total <- ncell(rb)\n",
        "    n_na    <- global(is.na(rb), \"sum\", na.rm=TRUE)[1,1]\n",
        "    n_ones  <- global(rb == 1, \"sum\", na.rm=TRUE)[1,1]\n",
        "    n_zeros <- global(rb == 0, \"sum\", na.rm=TRUE)[1,1]\n",
        "    summary_list[[i]] <- data.frame(\n",
        "      year=yrs[i], zeros=n_zeros, ones=n_ones, nas=n_na,\n",
        "      pct_0=round(100*n_zeros/n_total,4),\n",
        "      pct_1=round(100*n_ones /n_total,4),\n",
        "      pct_na=round(100*n_na  /n_total,4)\n",
        "    )\n",
        "    rm(r, r_crop, r_mask, rb); gc()\n",
        "  }\n",
        "  summary_df <- do.call(rbind, summary_list)\n",
        "  data.table::fwrite(summary_df, file.path(dir_forest, \"forest_bin_summary_by_year.csv\"))\n",
        "  log(\"STEP 1 ✅\")\n",
        "} else log(\"STEP 1 ⏭\")\n",
        "\n",
        "# ============================================================\n",
        "# STEP 2 — Distancia a borde (metros) por año\n",
        "# ============================================================\n",
        "if (RUN_STEP2_DISTEDGE) {\n",
        "  log(\"STEP 2: Distancia a borde bosque–no bosque (m)\")\n",
        "  fs_forest <- list.files(dir_forest, pattern=\"^forest01_\\\\d{4}\\\\.tif$\", full.names=TRUE)\n",
        "  stopifnot(\"No hay forest01_YYYY.tif\" = length(fs_forest) > 0)\n",
        "  yrs <- as.integer(gsub(\".*forest01_(\\\\d{4})\\\\.tif$\", \"\\\\1\", fs_forest))\n",
        "  ord <- order(yrs); fs_forest <- fs_forest[ord]; yrs <- yrs[ord]\n",
        "\n",
        "  for (i in seq_along(fs_forest)) {\n",
        "    in_path <- fs_forest[i]\n",
        "    yr      <- yrs[i]\n",
        "    out_path <- file.path(dir_distedge, sprintf(\"dist_edge_%d.tif\", yr))\n",
        "    if (file.exists(out_path)) { log(\"• Ya existe:\", basename(out_path)); next }\n",
        "    r <- rast(in_path)\n",
        "    # reproyección temporal si lon/lat\n",
        "    need_reproj <- is.lonlat(r)\n",
        "    r_m <- if (need_reproj) project(r, crs_metric, method=\"near\") else r\n",
        "    # fuente de distancia = NO-bosque (0→1); bosque (1→NA)\n",
        "    src_nonforest <- classify(r_m, rcl = rbind(c(0,1), c(1,NA)), include.lowest = TRUE)\n",
        "    d_all <- distance(src_nonforest)\n",
        "    forest_mask <- classify(r_m, rcl = rbind(c(1,1), c(0,NA)), include.lowest = TRUE)\n",
        "    dist_edge_m <- d_all * forest_mask; names(dist_edge_m) <- \"dist_edge_m\"\n",
        "    # devolver al grid original si reproyectaste\n",
        "    if (need_reproj) dist_edge_m <- project(dist_edge_m, r, method = \"bilinear\")\n",
        "    write_tif(dist_edge_m, out_path, wopt=list(datatype=\"FLT4S\"))\n",
        "    log(\"✔ Guardado:\", out_path)\n",
        "    rm(r, r_m, src_nonforest, d_all, forest_mask, dist_edge_m); gc()\n",
        "  }\n",
        "  log(\"STEP 2 ✅\")\n",
        "} else log(\"STEP 2 ⏭\")\n",
        "\n",
        "# ============================================================\n",
        "# STEP 3 — Máscaras de transición (defor 1→0; estable 1→1)\n",
        "# ============================================================\n",
        "if (RUN_STEP3_TRANS) {\n",
        "  log(\"STEP 3: Transiciones 1→0 y 1→1\")\n",
        "  write_transition_masks <- function(t_prev, t_curr) {\n",
        "    f_prev <- rast(file.path(dir_forest,   sprintf(\"forest01_%d.tif\", t_prev)))\n",
        "    f_curr <- rast(file.path(dir_forest,   sprintf(\"forest01_%d.tif\", t_curr)))\n",
        "    de_prev<- rast(file.path(dir_distedge, sprintf(\"dist_edge_%d.tif\", t_prev)))\n",
        "    if (!same.crs(f_curr, f_prev)) f_curr <- project(f_curr, y=f_prev, method=\"near\")\n",
        "    f_curr  <- resample(f_curr, f_prev, method=\"near\")\n",
        "    if (!same.crs(de_prev, f_prev)) de_prev <- project(de_prev, y=f_prev, method=\"bilinear\")\n",
        "    de_prev <- resample(de_prev, f_prev, method=\"bilinear\")\n",
        "    y_pos_r <- (f_prev == 1) & (f_curr == 0)\n",
        "    y_neg_r <- (f_prev == 1) & (f_curr == 1)\n",
        "    valid_de <- !is.na(de_prev)\n",
        "    pos_mask <- ifel(y_pos_r & valid_de, 1, NA)\n",
        "    neg_mask <- ifel(y_neg_r & valid_de, 1, NA)\n",
        "    wp <- list(gdal = c(\"COMPRESS=LZW\",\"TILED=YES\",\"BIGTIFF=IF_SAFER\"))\n",
        "    writeRaster(pos_mask, file.path(dir_trans, sprintf(\"trans_pos_%d_%d.tif\", t_prev, t_curr)), overwrite=TRUE, wopt=wp)\n",
        "    writeRaster(neg_mask, file.path(dir_trans, sprintf(\"trans_neg_%d_%d.tif\", t_prev, t_curr)), overwrite=TRUE, wopt=wp)\n",
        "    log(\"✔ Trans:\", t_prev, \"->\", t_curr)\n",
        "  }\n",
        "  # construir desde forest disponibles\n",
        "  years <- sort(as.integer(gsub(\".*forest01_(\\\\d{4})\\\\.tif$\", \"\\\\1\", list.files(dir_forest, full.names = TRUE))))\n",
        "  windows_all <- c(lapply(win_train, identity), list(win_valid), list(win_test))\n",
        "  for (w in windows_all) write_transition_masks(w[1], w[2])\n",
        "  log(\"STEP 3 ✅\")\n",
        "} else log(\"STEP 3 ⏭\")\n",
        "\n",
        "# ============================================================\n",
        "# STEP 4 — Muestreo desde transiciones + estáticos\n",
        "# ============================================================\n",
        "if (RUN_STEP4_SAMPLE) {\n",
        "  log(\"STEP 4: Muestreo supervisado\")\n",
        "\n",
        "  save_samples <- function(dt, out_csv) {\n",
        "    if (\"dist_edge\" %in% names(dt)) dt <- dt[!is.na(dist_edge)]\n",
        "    data.table::fwrite(dt, out_csv); log(\"Guardado:\", out_csv, \"| n =\", nrow(dt))\n",
        "  }\n",
        "  sample_cells_mask <- function(mask, n, seed = 42, batch = NULL, max_tries = 50L) {\n",
        "    set.seed(seed)\n",
        "    n_total <- as.integer(global(!is.na(mask), \"sum\", na.rm = TRUE)[1,1])\n",
        "    if (!is.finite(n_total) || n_total == 0) return(integer(0))\n",
        "    n <- min(n, n_total); if (n == 0) return(integer(0))\n",
        "    if (is.null(batch)) batch <- max(2L * n, 10000L)\n",
        "    picked <- integer(0); tries <- 0L; nc <- ncell(mask)\n",
        "    while (length(picked) < n && tries < max_tries) {\n",
        "      tries <- tries + 1L\n",
        "      cand <- sample.int(nc, size = batch, replace = FALSE)\n",
        "      xy   <- xyFromCell(mask, cand)\n",
        "      val  <- tryCatch(terra::extract(mask, vect(xy, crs = crs(mask)), ID = FALSE)[,1],\n",
        "                       error = function(e) rep(NA_real_, nrow(xy)))\n",
        "      ok   <- !is.na(val)\n",
        "      if (any(ok)) {\n",
        "        good_cells <- cand[ok]\n",
        "        picked <- unique(c(picked, good_cells))\n",
        "        if (length(picked) > n) picked <- picked[seq_len(n)]\n",
        "      }\n",
        "    }\n",
        "    picked\n",
        "  }\n",
        "  extract_static_by_pts <- function(paths, pts_in_ref_crs, method_map = NULL) {\n",
        "    out <- vector(\"list\", length(paths))\n",
        "    nm  <- gsub(\"\\\\.tif$\", \"\", basename(paths))\n",
        "    for (i in seq_along(paths)) {\n",
        "      r <- rast(paths[i])\n",
        "      pts_curr <- if (!same.crs(r, pts_in_ref_crs)) project(pts_in_ref_crs, crs(r)) else pts_in_ref_crs\n",
        "      m <- if (!is.null(method_map) && nm[i] %in% names(method_map)) method_map[[nm[i]]] else \"bilinear\"\n",
        "      out[[i]] <- tryCatch(extract(r, pts_curr, ID = FALSE, method = m)[,1],\n",
        "                           error = function(e) rep(NA_real_, nrow(pts_curr)))\n",
        "    }\n",
        "    names(out) <- nm; as.data.frame(out)\n",
        "  }\n",
        "  sample_from_transition <- function(t_prev, t_curr, out_csv, npos=10000, nneg=10000, seed=42) {\n",
        "    pos_path <- file.path(dir_trans,    sprintf(\"trans_pos_%d_%d.tif\", t_prev, t_curr))\n",
        "    neg_path <- file.path(dir_trans,    sprintf(\"trans_neg_%d_%d.tif\", t_prev, t_curr))\n",
        "    de_path  <- file.path(dir_distedge, sprintf(\"dist_edge_%d.tif\",     t_prev))\n",
        "    stopifnot(file.exists(pos_path), file.exists(neg_path), file.exists(de_path))\n",
        "    pos_mask <- rast(pos_path); neg_mask <- rast(neg_path); de_prev  <- rast(de_path)\n",
        "    if (!same.crs(de_prev, pos_mask)) de_prev <- project(de_prev, y = pos_mask, method = \"bilinear\")\n",
        "    de_prev <- resample(de_prev, pos_mask, method = \"bilinear\")\n",
        "    npos_avail <- as.integer(global(!is.na(pos_mask), \"sum\", na.rm=TRUE)[1,1])\n",
        "    nneg_avail <- as.integer(global(!is.na(neg_mask), \"sum\", na.rm=TRUE)[1,1])\n",
        "    stopifnot(npos_avail > 0, nneg_avail > 0)\n",
        "    npos_eff <- min(npos, npos_avail); nneg_eff <- min(nneg, nneg_avail)\n",
        "    pos_cells <- sample_cells_mask(pos_mask, npos_eff, seed = seed,      batch = max(4L*npos_eff, 20000L))\n",
        "    neg_cells <- sample_cells_mask(neg_mask, nneg_eff, seed = seed + 17, batch = max(4L*nneg_eff, 20000L))\n",
        "    stopifnot(length(pos_cells) > 0, length(neg_cells) > 0)\n",
        "    xy_pos <- xyFromCell(pos_mask, pos_cells); pts_pos <- vect(xy_pos, crs = crs(pos_mask))\n",
        "    xy_neg <- xyFromCell(neg_mask, neg_cells); pts_neg <- vect(xy_neg, crs = crs(neg_mask))\n",
        "    de_pos <- extract(de_prev, pts_pos, ID = FALSE)[,1]\n",
        "    de_neg <- extract(de_prev, pts_neg, ID = FALSE)[,1]\n",
        "    method_map <- NULL\n",
        "    Xs_pos <- extract_static_by_pts(static_paths, pts_pos, method_map)\n",
        "    Xs_neg <- extract_static_by_pts(static_paths, pts_neg, method_map)\n",
        "    dt_pos <- data.table::as.data.table(Xs_pos); dt_pos[, dist_edge := de_pos][, y := 1L][, `:=`(t_prev=t_prev, t_curr=t_curr)]\n",
        "    dt_neg <- data.table::as.data.table(Xs_neg); dt_neg[, dist_edge := de_neg][, y := 0L][, `:=`(t_prev=t_prev, t_curr=t_curr)]\n",
        "    dt <- data.table::rbindlist(list(dt_pos, dt_neg), use.names = TRUE, fill = TRUE)\n",
        "    save_samples(dt, out_csv); invisible(TRUE)\n",
        "  }\n",
        "\n",
        "  # Ejecutar\n",
        "  summary_rows <- list()\n",
        "  for (w in win_train) {\n",
        "    out_csv <- file.path(dir_samples, sprintf(\"train_%d_%d.csv\", w[1], w[2]))\n",
        "    if (!file.exists(out_csv)) try(sample_from_transition(w[1], w[2], out_csv, npos, nneg), silent = TRUE)\n",
        "    if (file.exists(out_csv)) {\n",
        "      df <- data.table::fread(out_csv, nThread = 1L)\n",
        "      summary_rows[[length(summary_rows)+1]] <- data.frame(split=\"train\", t_prev=w[1], t_curr=w[2],\n",
        "                                                           n=nrow(df), pos=sum(df$y==1L), neg=sum(df$y==0L))\n",
        "    }\n",
        "  }\n",
        "  valid_csv <- file.path(dir_samples, sprintf(\"valid_%d_%d.csv\", win_valid[1], win_valid[2]))\n",
        "  if (!file.exists(valid_csv)) try(sample_from_transition(win_valid[1], win_valid[2], valid_csv, npos, nneg), silent = TRUE)\n",
        "  if (file.exists(valid_csv)) {\n",
        "    df <- data.table::fread(valid_csv, nThread = 1L)\n",
        "    summary_rows[[length(summary_rows)+1]] <- data.frame(split=\"valid\", t_prev=win_valid[1], t_curr=win_valid[2],\n",
        "                                                         n=nrow(df), pos=sum(df$y==1L), neg=sum(df$y==0L))\n",
        "  }\n",
        "  test_csv <- file.path(dir_samples, sprintf(\"test_%d_%d.csv\", win_test[1], win_test[2]))\n",
        "  if (!file.exists(test_csv)) try(sample_from_transition(win_test[1], win_test[2], test_csv, npos, nneg), silent = TRUE)\n",
        "  if (file.exists(test_csv)) {\n",
        "    df <- data.table::fread(test_csv, nThread = 1L)\n",
        "    summary_rows[[length(summary_rows)+1]] <- data.frame(split=\"test\", t_prev=win_test[1], t_curr=win_test[2],\n",
        "                                                         n=nrow(df), pos=sum(df$y==1L), neg=sum(df$y==0L))\n",
        "  }\n",
        "  if (length(summary_rows)) {\n",
        "    sampling_summary <- dplyr::bind_rows(summary_rows)\n",
        "    data.table::fwrite(sampling_summary, file.path(dir_samples, \"sampling_summary.csv\"))\n",
        "    log(\"Resumen -> samples/sampling_summary.csv\")\n",
        "  }\n",
        "  log(\"STEP 4 ✅\")\n",
        "} else log(\"STEP 4 ⏭\")\n",
        "\n",
        "# ============================================================\n",
        "# STEP 5 — XGBoost: entrenamiento/evaluación/exportes\n",
        "# ============================================================\n",
        "if (RUN_STEP5_XGB) {\n",
        "  log(\"STEP 5: XGBoost\")\n",
        "  fpath <- function(tag) file.path(dir_samples, tag)\n",
        "  read_split <- function(path) {\n",
        "    dt <- data.table::fread(path); stopifnot(\"y\" %in% names(dt))\n",
        "    dt[, y := as.integer(y)]\n",
        "    drop <- intersect(c(\"t_prev\",\"t_curr\"), names(dt)); if (length(drop)) dt[, (drop) := NULL]\n",
        "    feats <- setdiff(names(dt), \"y\"); for (v in feats) dt[[v]] <- as.numeric(dt[[v]])\n",
        "    dt\n",
        "  }\n",
        "  # Cargar splits\n",
        "  train_tags <- c(\"train_2000_2005.csv\",\"train_2005_2010.csv\",\"train_2010_2015.csv\")\n",
        "  valid_tag  <- \"valid_2015_2020.csv\"\n",
        "  test_tag   <- \"test_2020_2023.csv\"\n",
        "  dtrain <- data.table::rbindlist(lapply(train_tags, \\(t) read_split(fpath(t))), use.names=TRUE, fill=TRUE)\n",
        "  dvalid <- read_split(fpath(valid_tag))\n",
        "  dtest  <- read_split(fpath(test_tag))\n",
        "  log(\"Train:\", nrow(dtrain), \"| Valid:\", nrow(dvalid), \"| Test:\", nrow(dtest))\n",
        "  features <- Reduce(intersect, list(setdiff(names(dtrain),\"y\"), setdiff(names(dvalid),\"y\"), setdiff(names(dtest),\"y\")))\n",
        "  stopifnot(length(features) > 0); features <- sort(features)\n",
        "  # Matrices\n",
        "  Xtr <- as.matrix(dtrain[, ..features]); ytr <- dtrain$y\n",
        "  Xva <- as.matrix(dvalid[, ..features]); yva <- dvalid$y\n",
        "  Xte <- as.matrix(dtest[,  ..features]); yte <- dtest$y\n",
        "  # Pesos por desbalance\n",
        "  pos_ratio <- sum(ytr == 0) / max(1, sum(ytr == 1))\n",
        "  spw <- if (abs(pos_ratio - 1) < 0.25) 1 else pos_ratio\n",
        "  params <- list(\n",
        "    objective = \"binary:logistic\", eval_metric = \"auc\",\n",
        "    eta = 0.05, max_depth = 6, min_child_weight = 5,\n",
        "    subsample = 0.8, colsample_bytree = 0.8,\n",
        "    lambda = 1.0, alpha = 0.0, scale_pos_weight = spw\n",
        "  )\n",
        "  dtr <- xgb.DMatrix(Xtr, label=ytr, missing=NA)\n",
        "  dva <- xgb.DMatrix(Xva, label=yva, missing=NA)\n",
        "  dte <- xgb.DMatrix(Xte, label=yte, missing=NA)\n",
        "  # Entrenamiento con early stopping\n",
        "  set.seed(42)\n",
        "  bst <- xgb.train(params=params, data=dtr, nrounds=5000,\n",
        "                   watchlist=list(train=dtr, eval=dva),\n",
        "                   early_stopping_rounds=100, verbose=1)\n",
        "  best_iter <- bst$best_iteration; best_score <- bst$best_score\n",
        "  log(\"best_iteration =\", best_iter, \"| best_valid_AUC =\", round(best_score, 4))\n",
        "  # Predicciones / métricas\n",
        "  pred_va <- predict(bst, dva); pred_te <- predict(bst, dte)\n",
        "  auc_va <- as.numeric(pROC::auc(response=yva, predictor=pred_va))\n",
        "  auc_te <- as.numeric(pROC::auc(response=yte, predictor=pred_te))\n",
        "  pra_va <- PRROC::pr.curve(scores.class0=pred_va[yva==1], scores.class1=pred_va[yva==0])$auc.integral\n",
        "  pra_te <- PRROC::pr.curve(scores.class0=pred_te[yte==1], scores.class1=pred_te[yte==0])$auc.integral\n",
        "  brier  <- function(p, y) mean((p - y)^2)\n",
        "  brier_va <- brier(pred_va, yva); brier_te <- brier(pred_te, yte)\n",
        "  # Umbral óptimo (F1) en valid\n",
        "  f1_at_thr <- function(p, y, thr) {\n",
        "    yhat <- as.integer(p >= thr)\n",
        "    tp <- sum(yhat==1 & y==1); fp <- sum(yhat==1 & y==0); fn <- sum(yhat==0 & y==1)\n",
        "    prec <- if ((tp+fp)==0) 0 else tp/(tp+fp); rec <- if ((tp+fn)==0) 0 else tp/(tp+fn)\n",
        "    if (prec+rec==0) return(0); 2*prec*rec/(prec+rec)\n",
        "  }\n",
        "  thr_grid <- seq(0.05, 0.95, 0.01)\n",
        "  thr_opt  <- thr_grid[ which.max(sapply(thr_grid, \\(t) f1_at_thr(pred_va, yva, t))) ]\n",
        "  # Métricas de test con thr_opt\n",
        "  yhat_te <- as.integer(pred_te >= thr_opt)\n",
        "  tp <- sum(yhat_te==1 & yte==1); fp <- sum(yhat_te==1 & yte==0)\n",
        "  tn <- sum(yhat_te==0 & yte==0); fn <- sum(yhat_te==0 & yte==1)\n",
        "  precision <- if ((tp+fp)==0) 0 else tp/(tp+fp)\n",
        "  recall    <- if ((tp+fn)==0) 0 else tp/(tp+fn)\n",
        "  f1_te     <- if ((precision+recall)==0) 0 else 2*precision*recall/(precision+recall)\n",
        "  acc_te    <- (tp+tn)/max(1,(tp+tn+fp+fn))\n",
        "  log(sprintf(\"VALID | AUC=%.4f  PR-AUC=%.4f  Brier=%.4f\", auc_va, pra_va, brier_va))\n",
        "  log(sprintf(\"TEST  | AUC=%.4f  PR-AUC=%.4f  Brier=%.4f  Acc=%.3f  F1=%.3f (thr=%.2f)\",\n",
        "              auc_te, pra_te, brier_te, acc_te, f1_te, thr_opt))\n",
        "  # Exportes\n",
        "  saveRDS(bst, file.path(dir_models, \"xgb_defrisk_model.rds\"))\n",
        "  data.table::fwrite(data.frame(threshold = thr_opt), file.path(dir_models, \"xgb_threshold.csv\"))\n",
        "  imp <- xgb.importance(model=bst, feature_names=features)\n",
        "  data.table::fwrite(imp, file.path(dir_models, \"feature_importance.csv\"))\n",
        "  metrics_df <- data.frame(\n",
        "    split=c(\"valid\",\"test\"), auc=c(auc_va,auc_te), pr_auc=c(pra_va,pra_te),\n",
        "    brier=c(brier_va,brier_te), acc=c(NA,acc_te), f1=c(NA,f1_te), thr=c(thr_opt,thr_opt),\n",
        "    tp=c(NA,tp), fp=c(NA,fp), tn=c(NA,tn), fn=c(NA,fn), precision=c(NA,precision),\n",
        "    recall=c(NA,recall)\n",
        "  )\n",
        "  data.table::fwrite(metrics_df, file.path(dir_models, \"metrics_valid_test.csv\"))\n",
        "  # Reentrenar final (train+valid) con nrounds = best_iter\n",
        "  dtrain_full <- data.table::rbindlist(list(dtrain, dvalid), use.names=TRUE, fill=TRUE)\n",
        "  Xtr_full <- as.matrix(dtrain_full[, ..features]); ytr_full <- dtrain_full$y\n",
        "  dtr_full <- xgb.DMatrix(Xtr_full, label=ytr_full, missing=NA)\n",
        "  set.seed(42)\n",
        "  bst_final <- xgb.train(params=params, data=dtr_full, nrounds=best_iter, verbose=1)\n",
        "  saveRDS(bst_final, file.path(dir_models, \"xgb_defrisk_model_final.rds\"))\n",
        "  data.table::fwrite(data.frame(threshold = thr_opt), file.path(dir_models, \"xgb_threshold_final.csv\"))\n",
        "  imp_final <- xgb.importance(model=bst_final, feature_names=features)\n",
        "  data.table::fwrite(imp_final, file.path(dir_models, \"feature_importance_final.csv\"))\n",
        "  log(\"STEP 5 ✅  (modelo y umbral en 'models/')\")\n",
        "\n",
        "} else log(\"STEP 5 ⏭\")\n",
        "\n",
        "# ============================================================\n",
        "# STEP 6 — Inferencia a rejilla (probabilidad/binario/acumulada)\n",
        "# ============================================================\n",
        "if (RUN_STEP6_INFER) {\n",
        "  log(\"STEP 6: Inferencia a rejilla\")\n",
        "  model_path <- file.path(dir_models, \"xgb_defrisk_model_final.rds\")\n",
        "  stopifnot(file.exists(model_path))\n",
        "  bst_final <- readRDS(model_path)\n",
        "  thr_file_final <- file.path(dir_models, \"xgb_threshold_final.csv\")\n",
        "  thr_file_fbk   <- file.path(dir_models, \"xgb_threshold.csv\")\n",
        "  thr_opt <- if (file.exists(thr_file_final)) {\n",
        "    as.numeric(data.table::fread(thr_file_final)$threshold[1])\n",
        "  } else if (file.exists(thr_file_fbk)) {\n",
        "    as.numeric(data.table::fread(thr_file_fbk)$threshold[1])\n",
        "  } else 0.5\n",
        "  if (!is.finite(thr_opt)) thr_opt <- 0.5\n",
        "  # Validar features esperadas\n",
        "  fi_path <- file.path(dir_models, \"feature_importance_final.csv\")\n",
        "  if (!file.exists(fi_path)) fi_path <- file.path(dir_models, \"feature_importance.csv\")\n",
        "  features_expected <- if (file.exists(fi_path)) unique(data.table::fread(fi_path)$Feature) else names(paths_infer)\n",
        "  if (!setequal(names(paths_infer), features_expected)) {\n",
        "    missing_in_paths <- setdiff(features_expected, names(paths_infer))\n",
        "    extra_in_paths   <- setdiff(names(paths_infer), features_expected)\n",
        "    stop(\"Desajuste de features para inferencia.\\nFaltan en 'paths_infer': \", paste(missing_in_paths, collapse=\", \"),\n",
        "         \"\\nSobran en 'paths_infer': \", paste(extra_in_paths, collapse=\", \"))\n",
        "  }\n",
        "  paths_infer <- paths_infer[features_expected]  # orden exacto\n",
        "  # Construir stack predictor\n",
        "  pred_stack <- rast(unname(paths_infer)); names(pred_stack) <- names(paths_infer)\n",
        "  if (use_forest_mask) {\n",
        "    tpl <- rast(forest_mask_file)\n",
        "    if (!identical(crs(tpl), crs(pred_stack))) tpl <- project(tpl, pred_stack, method=\"near\")\n",
        "    tpl <- resample(tpl, pred_stack, method=\"near\")\n",
        "    pred_stack <- mask(pred_stack, ifel(tpl==1, 1, NA))\n",
        "  }\n",
        "  # Predict por bloques\n",
        "  xgb_fun <- function(model, data, ...) { data <- as.matrix(data); as.numeric(predict(model, data)) }\n",
        "  wp_prob <- list(datatype = \"FLT4S\",\n",
        "                  gdal = c(\"COMPRESS=ZSTD\",\"NUM_THREADS=ALL_CPUS\",\"TILED=YES\",\"BIGTIFF=IF_SAFER\",\"BLOCKXSIZE=512\",\"BLOCKYSIZE=512\"))\n",
        "  wp_bin  <- list(datatype = \"INT1U\", gdal = c(\"COMPRESS=LZW\",\"TILED=YES\",\"BIGTIFF=IF_SAFER\"))\n",
        "  prob_tif <- file.path(dir_riskmaps, sprintf(\"defrisk_prob_%d_%s.tif\", base_year, res_tag))\n",
        "  bin_tif  <- file.path(dir_riskmaps, sprintf(\"defrisk_bin_%d_%s_thr.tif\",  base_year, res_tag))\n",
        "  log(\"→ Prediciendo probabilidad…\")\n",
        "  prob <- terra::predict(pred_stack, model=bst_final, fun=xgb_fun,\n",
        "                         filename=prob_tif, overwrite=TRUE, wopt=wp_prob, progress=1)\n",
        "  names(prob) <- \"risk_prob\"; log(\"✔\", prob_tif)\n",
        "  # Binario\n",
        "  risk_bin <- ifel(prob >= thr_opt, 1, ifel(is.na(prob), NA, 0))\n",
        "  writeRaster(risk_bin, bin_tif, overwrite=TRUE, wopt=wp_bin); log(\"✔\", bin_tif)\n",
        "  # QA\n",
        "  n_total <- ncell(prob)\n",
        "  n_na    <- global(is.na(prob), \"sum\", na.rm = TRUE)[1,1]\n",
        "  n_ones  <- global(risk_bin == 1, \"sum\", na.rm = TRUE)[1,1]\n",
        "  n_zeros <- global(risk_bin == 0, \"sum\", na.rm = TRUE)[1,1]\n",
        "  p_mean  <- global(prob, \"mean\", na.rm = TRUE)[1,1]\n",
        "  p_med   <- global(prob, \"median\", na.rm = TRUE)[1,1]\n",
        "  p_q90   <- global(prob, \"quantile\", p=0.90, na.rm = TRUE)[1,1]\n",
        "  qa <- data.frame(base_year=base_year, res=res_tag, n_total=n_total, n_na=n_na, n_ones=n_ones, n_zeros=n_zeros,\n",
        "                   prob_mean=round(p_mean,6), prob_median=round(p_med,6), prob_q90=round(p_q90,6), thr=thr_opt)\n",
        "  data.table::fwrite(qa, file.path(dir_riskmaps, sprintf(\"inference_summary_%d.csv\", base_year)))\n",
        "  # Acumulada hasta target_year_cum\n",
        "  if (!is.null(target_year_cum) && target_year_cum > base_year) {\n",
        "    n_steps <- ceiling((target_year_cum - base_year) / window_years)\n",
        "    log(sprintf(\"→ Probabilidad acumulada hasta %d (n=%d pasos de %d años)…\", target_year_cum, n_steps, window_years))\n",
        "    prob_cum <- 1 - (1 - prob)^n_steps; names(prob_cum) <- \"risk_prob_cum\"\n",
        "    prob_cum_tif <- file.path(dir_riskmaps, sprintf(\"defrisk_prob_cum_to_%d_%s.tif\", target_year_cum, res_tag))\n",
        "    writeRaster(prob_cum, prob_cum_tif, overwrite=TRUE, wopt=wp_prob)\n",
        "    bin_cum_tif <- file.path(dir_riskmaps, sprintf(\"defrisk_bin_cum_to_%d_%s_thr.tif\", target_year_cum, res_tag))\n",
        "    risk_bin_cum <- ifel(prob_cum >= thr_opt, 1, ifel(is.na(prob_cum), NA, 0))\n",
        "    writeRaster(risk_bin_cum, bin_cum_tif, overwrite=TRUE, wopt=wp_bin)\n",
        "    log(\"✔\", prob_cum_tif); log(\"✔\", bin_cum_tif)\n",
        "  }\n",
        "  log(\"STEP 6 ✅\")\n",
        "} else log(\"STEP 6 ⏭\")\n",
        "\n",
        "log(\"✓ Pipeline completado.\")\n"
      ]
    }
  ]
}