{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyN0M6JupF+9vCdxvyS4d+xK",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/hmg8906/CienciaDatosCN/blob/TFM/master_SDM.R\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "WvTuEnQTG9i0"
      },
      "outputs": [],
      "source": [
        "# =========================================================\n",
        "# sdm_master.R  —  Flujo completo SDM (conciliación → GBIF → MaxEnt → riqueza)\n",
        "# =========================================================\n",
        "# Requisitos: R 4.x; Java instalado; dismo con maxent.jar disponible.\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "# -------------------- PARAMS (EDITA AQUÍ) ----------------\n",
        "DIR_BASE   <- \"C:/Users/henry.garcia/Desktop/Primates\"\n",
        "\n",
        "# Entradas\n",
        "PRIMATES_LISTA_CSV <- file.path(DIR_BASE, \"primates_lista.csv\")           # lista inicial de especies\n",
        "PRESENT_TIF        <- \"C:/Users/henry.garcia/Desktop/Primates/predictors/climate/predictors_vif/present_VIFsel.tif\"\n",
        "FUTURES            <- list(\n",
        "  list(tag=\"ssp585_2040\",\n",
        "       tif=\"C:/Users/henry.garcia/Desktop/Primates/predictors/climate/predictors_vif/future_ssp585_2040_VIFsel.tif\")\n",
        ")\n",
        "\n",
        "# Salidas y rutas intermedias\n",
        "PATH_CONC          <- file.path(DIR_BASE, \"primates_backbone_conciliacion.csv\")\n",
        "GBIF_DIR           <- file.path(DIR_BASE, \"output_gbif\")\n",
        "GBIF_RAW_CSV       <- file.path(GBIF_DIR, \"gbif_presencia_raw.csv\")\n",
        "GBIF_FINAL_CSV     <- file.path(GBIF_DIR, \"gbif_presencia_filtrada.csv\")\n",
        "MODELS_DIR         <- file.path(DIR_BASE, \"models_maxent_ALL_with_future\") # usado también por 'riqueza'\n",
        "RICH_OUT_DIR       <- file.path(MODELS_DIR, \"richness_maps\")\n",
        "\n",
        "# Parámetros GBIF\n",
        "YEAR_MIN <- 1970\n",
        "YEAR_MAX <- as.integer(format(Sys.Date(), \"%Y\"))\n",
        "BASIS_OF_RECORD <- NULL   # p.ej., c(\"HUMAN_OBSERVATION\",\"PRESERVED_SPECIMEN\")\n",
        "\n",
        "# Ejecutar pasos\n",
        "RUN_STEP_1_CONCILIACION <- TRUE\n",
        "RUN_STEP_2_GBIF         <- TRUE\n",
        "RUN_STEP_3_MAXENT       <- TRUE\n",
        "RUN_STEP_4_RIQUEZA      <- TRUE\n",
        "# ---------------------------------------------------------\n",
        "\n",
        "set.seed(123)\n",
        "options(java.parameters = \"-Xmx4g\")  # ajusta según tu RAM\n",
        "\n",
        "# Paquetes base\n",
        "pkgs <- c(\n",
        "  \"readr\",\"dplyr\",\"data.table\",\"stringr\",\"purrr\",\n",
        "  \"rgbif\",\"terra\",\"sf\",\"raster\",\"dismo\"\n",
        ")\n",
        "new <- pkgs[!pkgs %in% installed.packages()[,\"Package\"]]\n",
        "if (length(new)) install.packages(new, dependencies = TRUE)\n",
        "invisible(lapply(pkgs, library, character.only = TRUE))\n",
        "\n",
        "# Utilidades\n",
        "`%||%` <- function(a,b) if (!is.null(a)) a else b\n",
        "auto_assert <- function(cond, msg) if (!cond) stop(msg)\n",
        "\n",
        "dir.create(DIR_BASE, showWarnings = FALSE, recursive = TRUE)\n",
        "dir.create(GBIF_DIR,   showWarnings = FALSE, recursive = TRUE)\n",
        "dir.create(MODELS_DIR, showWarnings = FALSE, recursive = TRUE)\n",
        "\n",
        "# =========================================================\n",
        "# STEP 1 — Conciliación taxonómica (GBIF backbone)\n",
        "# =========================================================\n",
        ".clean_sciname <- function(x) {\n",
        "  x %>% as.character() %>% stringr::str_squish() %>%\n",
        "    stringr::str_replace(\"\\\\s*\\\\([^)]*\\\\)\\\\s*$\", \"\") %>%\n",
        "    stringr::str_replace_all(\"(?i)\\\\b(cf\\\\.|aff\\\\.|sp\\\\.?|spp\\\\.?|s\\\\.l\\\\.|s\\\\.s\\\\.|\\\\?)\\\\b\", \"\") %>%\n",
        "    stringr::str_squish()\n",
        "}\n",
        "backbone_conciliar <- function(df, name_col = \"scientificName\", enforce_primates = TRUE) {\n",
        "  stopifnot(name_col %in% names(df))\n",
        "  nombres <- .clean_sciname(df[[name_col]]) %>% unique()\n",
        "  pb <- utils::txtProgressBar(min = 0, max = length(nombres), style = 3); i <- 0L\n",
        "  resolver_uno <- function(sci) {\n",
        "    on.exit({ i <<- i + 1L; utils::setTxtProgressBar(pb, i) }, add = TRUE)\n",
        "    out <- tryCatch({\n",
        "      parts <- strsplit(sci, \"\\\\s+\")[[1]]\n",
        "      bb <- rgbif::name_backbone(name = sci, rank = \"SPECIES\")\n",
        "      if (is.null(bb$usageKey) && length(parts)>=2)\n",
        "        bb <- rgbif::name_backbone(name = paste(parts[1],parts[2]), rank=\"SPECIES\")\n",
        "      if (is.null(bb$usageKey) && length(parts)>=1)\n",
        "        bb <- rgbif::name_backbone(name = parts[1], rank=\"GENUS\")\n",
        "      if (is.null(bb$usageKey)) {\n",
        "        return(tibble::tibble(scientificName_input=sci, gbif_scientificName=NA_character_, acceptedUsageKey=NA_integer_))\n",
        "      }\n",
        "      if (isTRUE(enforce_primates) && !identical(bb$order,\"Primates\"))\n",
        "        return(tibble::tibble(scientificName_input=sci, gbif_scientificName=NA_character_, acceptedUsageKey=NA_integer_))\n",
        "      key <- bb$acceptedUsageKey %||% bb$usageKey %||% NA_integer_\n",
        "      nm  <- bb$scientificName %||% NA_character_\n",
        "      tibble::tibble(scientificName_input=sci, gbif_scientificName=nm, acceptedUsageKey=as.integer(key))\n",
        "    }, error = function(e) tibble::tibble(scientificName_input=sci, gbif_scientificName=NA_character_, acceptedUsageKey=NA_integer_))\n",
        "    if (length(nombres) > 100) Sys.sleep(0.05)\n",
        "    out\n",
        "  }\n",
        "  res <- purrr::map_dfr(nombres, resolver_uno); close(pb); res\n",
        "}\n",
        "\n",
        "if (RUN_STEP_1_CONCILIACION) {\n",
        "  auto_assert(file.exists(PRIMATES_LISTA_CSV),\n",
        "              paste(\"No existe el CSV de entrada con la lista de especies:\", PRIMATES_LISTA_CSV))\n",
        "  sp <- readr::read_csv(PRIMATES_LISTA_CSV, show_col_types = FALSE)\n",
        "  auto_assert(\"scientificName\" %in% names(sp),\n",
        "              \"Se espera una columna 'scientificName' en primates_lista.csv\")\n",
        "\n",
        "  conc <- backbone_conciliar(sp, name_col = \"scientificName\", enforce_primates = TRUE)\n",
        "  conc_export <- conc %>% dplyr::select(scientificName_input, gbif_scientificName, acceptedUsageKey)\n",
        "  readr::write_csv(conc_export, PATH_CONC)\n",
        "\n",
        "  n_ok   <- sum(!is.na(conc_export$acceptedUsageKey))\n",
        "  n_fail <- sum(is.na(conc_export$acceptedUsageKey))\n",
        "  cat(\"STEP1 ✅ Conciliación ->\", PATH_CONC, \"| OK:\", n_ok, \"| Sin match:\", n_fail, \"\\n\")\n",
        "} else {\n",
        "  cat(\"STEP1 ⏭ Saltado (se asume PATH_CONC existente)\\n\")\n",
        "}\n",
        "\n",
        "# =========================================================\n",
        "# STEP 2 — Descarga/curaduría de ocurrencias (GBIF API)\n",
        "# =========================================================\n",
        "fetch_occ_all <- function(taxonKey, hasCoordinate=TRUE, basisOfRecord=NULL, year=NULL,\n",
        "                          page_size=300, max_records=1e6) {\n",
        "  offset <- 0L; out <- list()\n",
        "  repeat {\n",
        "    dat <- tryCatch({\n",
        "      rgbif::occ_search(\n",
        "        taxonKey = taxonKey, hasCoordinate = hasCoordinate,\n",
        "        basisOfRecord = basisOfRecord, year = year,\n",
        "        limit = page_size, start = offset\n",
        "      )$data\n",
        "    }, error=function(e) NULL)\n",
        "    if (is.null(dat) || nrow(dat)==0) break\n",
        "    out[[length(out)+1L]] <- dat\n",
        "    got <- nrow(dat); offset <- offset + got\n",
        "    if (got < page_size || offset >= max_records) break\n",
        "  }\n",
        "  if (length(out)) data.table::rbindlist(out, fill=TRUE) else NULL\n",
        "}\n",
        "fetch_with_retries <- function(taxonKey, hasCoordinate=TRUE, basisOfRecord=NULL, year=NULL, tries=4) {\n",
        "  res <- NULL\n",
        "  for (att in 0:(tries-1)) {\n",
        "    res <- tryCatch(fetch_occ_all(taxonKey, hasCoordinate, basisOfRecord, year), error=function(e) NULL)\n",
        "    if (!is.null(res) && nrow(res)>0) return(res)\n",
        "    Sys.sleep(min(60, (2^att) + stats::runif(1,0,0.7)))\n",
        "  }\n",
        "  res\n",
        "}\n",
        "\n",
        "if (RUN_STEP_2_GBIF) {\n",
        "  auto_assert(file.exists(PATH_CONC), paste(\"No existe el CSV de conciliación:\", PATH_CONC))\n",
        "  conc <- readr::read_csv(PATH_CONC, show_col_types = FALSE)\n",
        "  req_cols <- c(\"scientificName_input\",\"gbif_scientificName\",\"acceptedUsageKey\")\n",
        "  auto_assert(all(req_cols %in% names(conc)), \"Faltan columnas requeridas en conciliación.\")\n",
        "\n",
        "  conc <- conc %>%\n",
        "    mutate(\n",
        "      taxonKey = as.integer(acceptedUsageKey),\n",
        "      scientificName = ifelse(!is.na(gbif_scientificName) & nzchar(gbif_scientificName),\n",
        "                              gbif_scientificName, scientificName_input)\n",
        "    )\n",
        "  df_valid <- conc %>% filter(!is.na(taxonKey)) %>% distinct(taxonKey, scientificName, .keep_all = FALSE)\n",
        "  auto_assert(nrow(df_valid)>0, \"df_valid vacío: no hay acceptedUsageKey válidos.\")\n",
        "\n",
        "  if (file.exists(GBIF_RAW_CSV)) file.remove(GBIF_RAW_CSV)\n",
        "  failed_fetch <- character(0); total_records <- 0L\n",
        "  BATCH_SIZE <- 100\n",
        "  num_batches <- ceiling(nrow(df_valid)/BATCH_SIZE)\n",
        "\n",
        "  for (b in seq_len(num_batches)) {\n",
        "    idx  <- ((b-1)*BATCH_SIZE+1):min(b*BATCH_SIZE, nrow(df_valid))\n",
        "    lote <- df_valid[idx, ]\n",
        "    message(\"\\nSTEP2 ▶ Lote \", b, \"/\", num_batches, \" (\", nrow(lote), \" spp)\")\n",
        "\n",
        "    registros <- vector(\"list\", nrow(lote))\n",
        "    for (i in seq_len(nrow(lote))) {\n",
        "      key  <- lote$taxonKey[i]; name <- lote$scientificName[i]\n",
        "      res <- fetch_with_retries(\n",
        "        taxonKey = key, hasCoordinate = TRUE,\n",
        "        basisOfRecord = BASIS_OF_RECORD,\n",
        "        year = paste(YEAR_MIN, YEAR_MAX, sep = \",\"),\n",
        "        tries = 4\n",
        "      )\n",
        "      if (!is.null(res) && nrow(res)>0) {\n",
        "        if (!is.null(BASIS_OF_RECORD)) res <- dplyr::filter(res, basisOfRecord %in% BASIS_OF_RECORD)\n",
        "        if (!is.null(YEAR_MIN))        res <- dplyr::filter(res, !is.na(year) & year >= YEAR_MIN)\n",
        "        if (!is.null(YEAR_MAX))        res <- dplyr::filter(res, !is.na(year) & year <= YEAR_MAX)\n",
        "        if (nrow(res)>0) { res$scientificNameQueried <- name; registros[[i]] <- res }\n",
        "      } else failed_fetch <- c(failed_fetch, paste0(name,\"|\",key))\n",
        "    }\n",
        "\n",
        "    regs_non_null <- Filter(Negate(is.null), registros)\n",
        "    if (length(regs_non_null)) {\n",
        "      registros_batch <- dplyr::bind_rows(regs_non_null) %>% as.data.frame()\n",
        "      for (nn in c(\"gbifID\",\"occurrenceID\",\"eventDate\"))\n",
        "        if (nn %in% names(registros_batch)) registros_batch[[nn]] <- as.character(registros_batch[[nn]])\n",
        "\n",
        "      columnas_importantes <- c(\n",
        "        \"scientificNameQueried\",\"scientificName\",\"verbatimScientificName\",\n",
        "        \"kingdom\",\"phylum\",\"class\",\"order\",\"family\",\"genus\",\"species\",\"taxonRank\",\"taxonKey\",\n",
        "        \"gbifID\",\"occurrenceID\",\"occurrenceStatus\",\"basisOfRecord\",\n",
        "        \"eventDate\",\"year\",\"month\",\"day\",\n",
        "        \"decimalLatitude\",\"decimalLongitude\",\"coordinatePrecision\",\n",
        "        \"coordinateUncertaintyInMeters\",\"geodeticDatum\",\n",
        "        \"elevation\",\"elevationAccuracy\",\"depth\",\"depthAccuracy\",\n",
        "        \"country\",\"countryCode\",\"stateProvince\",\"county\",\"municipality\",\"locality\",\n",
        "        \"datasetKey\",\"publishingOrgKey\",\"license\",\n",
        "        \"institutionCode\",\"collectionCode\",\"catalogNumber\",\n",
        "        \"recordedBy\",\"identifiedBy\",\"samplingProtocol\",\"samplingEffort\",\n",
        "        \"issues\"\n",
        "      )\n",
        "      for (col in columnas_importantes) if (!col %in% names(registros_batch)) registros_batch[[col]] <- NA\n",
        "      keep <- intersect(columnas_importantes, names(registros_batch))\n",
        "      registros_batch <- registros_batch[, keep, drop = FALSE]\n",
        "\n",
        "      # aplanar list-cols si aparecen\n",
        "      list_cols <- names(registros_batch)[vapply(registros_batch, is.list, logical(1))]\n",
        "      if (length(list_cols)) {\n",
        "        registros_batch[list_cols] <- lapply(registros_batch[list_cols], function(v) {\n",
        "          vapply(v, function(x) if (is.null(x) || length(x) == 0) NA_character_ else paste0(as.character(unlist(x)), collapse = \";\"),\n",
        "                 character(1))\n",
        "        })\n",
        "      }\n",
        "\n",
        "      data.table::setDT(registros_batch)\n",
        "      if (\"gbifID\" %in% names(registros_batch)) registros_batch <- unique(registros_batch, by = \"gbifID\")\n",
        "      total_records <- total_records + nrow(registros_batch)\n",
        "      data.table::fwrite(registros_batch, GBIF_RAW_CSV,\n",
        "                         append = file.exists(GBIF_RAW_CSV),\n",
        "                         col.names = !file.exists(GBIF_RAW_CSV))\n",
        "      cat(\"   📦 Lote\", b, \"->\", nrow(registros_batch), \"registros guardados\\n\")\n",
        "    } else {\n",
        "      cat(\"   ⚠️ Lote\", b, \"sin registros válidos\\n\")\n",
        "    }\n",
        "    rm(registros); gc()\n",
        "  }\n",
        "\n",
        "  # CSV final compacto\n",
        "  if (file.exists(GBIF_RAW_CSV)) {\n",
        "    registros_todos <- readr::read_csv(GBIF_RAW_CSV, show_col_types = FALSE, guess_max = 100000)\n",
        "    if (\"gbifID\" %in% names(registros_todos)) {\n",
        "      data.table::setDT(registros_todos)\n",
        "      registros_todos <- unique(registros_todos, by = \"gbifID\")\n",
        "      registros_todos <- as.data.frame(registros_todos)\n",
        "    }\n",
        "    cols_final <- c(\n",
        "      \"scientificNameQueried\",\"scientificName\",\"taxonKey\",\"gbifID\",\"occurrenceID\",\"basisOfRecord\",\n",
        "      \"eventDate\",\"year\",\"month\",\"day\",\"decimalLatitude\",\"decimalLongitude\",\n",
        "      \"coordinateUncertaintyInMeters\",\"country\",\"countryCode\",\"stateProvince\",\"municipality\",\"locality\",\n",
        "      \"datasetKey\",\"license\",\"institutionCode\",\"collectionCode\",\"catalogNumber\",\"recordedBy\",\"identifiedBy\",\"issues\"\n",
        "    )\n",
        "    keep_final <- intersect(cols_final, names(registros_todos))\n",
        "    readr::write_csv(registros_todos[, keep_final, drop = FALSE], GBIF_FINAL_CSV)\n",
        "    message(\"STEP2 ✅ GBIF final -> \", GBIF_FINAL_CSV, \" | Registros: \", nrow(registros_todos))\n",
        "  } else {\n",
        "    stop(\"STEP2: No se generó GBIF_RAW_CSV; revisa conexión/queries.\")\n",
        "  }\n",
        "} else {\n",
        "  cat(\"STEP2 ⏭ Saltado (se asume GBIF_FINAL_CSV existente)\\n\")\n",
        "}\n",
        "\n",
        "# =========================================================\n",
        "# STEP 3 — Modelación MaxEnt (presente + futuros)\n",
        "# =========================================================\n",
        "safe_dir <- function(x) gsub(\"[^A-Za-z0-9_\\\\-]\", \"_\", x)\n",
        "haversine_km <- function(lon1, lat1, lon2, lat2){\n",
        "  rad <- pi/180; dlat <- (lat2-lat1)*rad; dlon <- (lon2-lon1)*rad\n",
        "  a <- sin(dlat/2)^2 + cos(lat1*rad)*cos(lat2*rad)*sin(dlon/2)^2\n",
        "  6371*2*atan2(sqrt(a), sqrt(1-a))\n",
        "}\n",
        "make_MCP_buffer_robusto <- function(pres_df, buffer_km=25, trim_q=0.995){\n",
        "  c_lon <- median(pres_df$lon); c_lat <- median(pres_df$lat)\n",
        "  d_km  <- haversine_km(pres_df$lon, pres_df$lat, c_lon, c_lat)\n",
        "  thr   <- as.numeric(quantile(d_km, trim_q, na.rm=TRUE))\n",
        "  keep  <- d_km <= thr\n",
        "  pres_trim <- pres_df[keep, , drop=FALSE]\n",
        "  pts_sf <- sf::st_as_sf(pres_trim, coords=c(\"lon\",\"lat\"), crs=4326)\n",
        "  mcp    <- pts_sf |> sf::st_union() |> sf::st_convex_hull()\n",
        "  mcp_buf <- mcp |> sf::st_transform(3857) |> sf::st_buffer(buffer_km*1000) |> sf::st_transform(4326)\n",
        "  list(M=mcp_buf, pres_trim=pres_trim, removed=sum(!keep), thr_km=thr, mcp=mcp)\n",
        "}\n",
        "normalize_names <- function(nm){\n",
        "  nm <- gsub(\"[\\u00A0\\u2007\\u202F]\", \" \", nm); nm <- gsub(\"\\\\.+\", \" \", nm); gsub(\"\\\\s+\", \" \", trimws(nm))\n",
        "}\n",
        "numify <- function(x){\n",
        "  v <- suppressWarnings(as.numeric(x))\n",
        "  if (any(is.na(v))) v <- suppressWarnings(readr::parse_number(x, locale=readr::locale(decimal_mark=\",\", grouping_mark=\".\")))\n",
        "  if (any(is.na(v))) v <- suppressWarnings(readr::parse_number(x, locale=readr::locale(decimal_mark=\".\", grouping_mark=\",\")))\n",
        "  v\n",
        "}\n",
        "getcol_exact <- function(df, label){\n",
        "  hits <- which(tolower(names(df)) == tolower(label)); if (length(hits)) names(df)[hits[1]] else character(0)\n",
        "}\n",
        "fc_to_args <- function(fc){\n",
        "  base <- c(\"autofeature=false\",\"linear=false\",\"quadratic=false\",\"product=false\",\"threshold=false\",\"hinge=false\")\n",
        "  c(base, if (grepl(\"L\",fc)) \"linear=true\",\n",
        "    if (grepl(\"Q\",fc)) \"quadratic=true\",\n",
        "    if (grepl(\"H\",fc)) \"hinge=true\",\n",
        "    if (grepl(\"P\",fc)) \"product=true\",\n",
        "    if (grepl(\"T\",fc)) \"threshold=true\")\n",
        "}\n",
        "guess_col <- function(df, candidates) {\n",
        "  hits <- names(df)[tolower(names(df)) %in% tolower(candidates)]\n",
        "  if (length(hits)) hits[1] else stop(\"No se encontraron columnas: \", paste(candidates, collapse=\", \"))\n",
        "}\n",
        "\n",
        "if (RUN_STEP_3_MAXENT) {\n",
        "  # Checks Java/MaxEnt\n",
        "  maxent_jar <- file.path(system.file(\"java\", package = \"dismo\"), \"maxent.jar\")\n",
        "  auto_assert(file.exists(maxent_jar), paste(\"No se encontró maxent.jar en dismo:\", maxent_jar, \"\\nInstala Java/dismo correctamente.\"))\n",
        "  auto_assert(file.exists(PRESENT_TIF), paste(\"No existe stack de predictores presente:\", PRESENT_TIF))\n",
        "  dir.create(MODELS_DIR, showWarnings = FALSE, recursive = TRUE)\n",
        "\n",
        "  # Occs (usa el CSV final del STEP2)\n",
        "  auto_assert(file.exists(GBIF_FINAL_CSV), paste(\"No existe GBIF_FINAL_CSV:\", GBIF_FINAL_CSV))\n",
        "  occ_raw <- readr::read_csv(GBIF_FINAL_CSV, show_col_types = FALSE)\n",
        "  col_species <- guess_col(occ_raw, c(\"species_bm\",\"species\",\"scientificName\",\"scientificname\",\"scientificNameQueried\"))\n",
        "  col_lon     <- guess_col(occ_raw, c(\"longitude\",\"decimalLongitude\",\"lon\"))\n",
        "  col_lat     <- guess_col(occ_raw, c(\"latitude\",\"decimalLatitude\",\"lat\"))\n",
        "\n",
        "  occ <- occ_raw %>%\n",
        "    transmute(\n",
        "      species = .data[[col_species]],\n",
        "      lon     = suppressWarnings(as.numeric(.data[[col_lon]])),\n",
        "      lat     = suppressWarnings(as.numeric(.data[[col_lat]]))\n",
        "    ) %>%\n",
        "    filter(is.finite(lon), is.finite(lat), !is.na(species)) %>%\n",
        "    distinct(species, lon, lat, .keep_all = TRUE)\n",
        "\n",
        "  sp_counts   <- occ %>% count(species, name=\"n_pres\") %>% filter(n_pres > 10) %>% arrange(species)\n",
        "  species_all <- sp_counts$species\n",
        "  auto_assert(length(species_all)>0, \"No hay especies con >10 presencias.\")\n",
        "\n",
        "  env_full <- terra::rast(PRESENT_TIF); names(env_full) <- paste0(\"v\", seq_len(nlyr(env_full)))\n",
        "  FC_SET <- c(\"LQ\",\"LQH\",\"LQHP\"); RM_SET <- c(0.5,1,2); REPS <- 5\n",
        "\n",
        "  run_one_species <- function(sp) {\n",
        "    out_dir <- file.path(MODELS_DIR, safe_dir(sp))\n",
        "    dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)\n",
        "    stats_csv <- file.path(out_dir, \"model_stats.csv\")\n",
        "    if (file.exists(stats_csv)) return(readr::read_csv(stats_csv, show_col_types = FALSE, n_max = 1))\n",
        "\n",
        "    pres_all <- occ %>% filter(species == sp) %>% select(lon, lat)\n",
        "    if (nrow(pres_all) <= 10) { writeLines(\"<=10 presencias\", con=file.path(out_dir,\"ERROR.txt\")); return(NULL) }\n",
        "\n",
        "    # Área M\n",
        "    Mres   <- make_MCP_buffer_robusto(pres_all, buffer_km=25, trim_q=0.995)\n",
        "    M_poly <- Mres$M\n",
        "    area_km2 <- as.numeric(sf::st_area(sf::st_transform(M_poly, 3857))) / 1e6\n",
        "    # Plot M\n",
        "    png(file.path(out_dir, \"area_M_plot.png\"), width=1200, height=900, res=150)\n",
        "    plot(sf::st_geometry(M_poly), col=adjustcolor(\"orange\",0.25), border=\"orange\", lwd=2,\n",
        "         main=sprintf(\"Área M ( %s )\", sp), reset=FALSE)\n",
        "    plot(sf::st_geometry(Mres$mcp), add=TRUE, col=NA, border=\"red\", lwd=2, lty=2)\n",
        "    in_idx <- paste(pres_all$lon, pres_all$lat) %in% paste(Mres$pres_trim$lon, Mres$pres_trim$lat)\n",
        "    if (any(in_idx))  points(pres_all$lon[in_idx],  pres_all$lat[in_idx],  pch=20, col=\"blue\")\n",
        "    if (any(!in_idx)) points(pres_all$lon[!in_idx], pres_all$lat[!in_idx], pch=4,  col=\"darkorange\", lwd=1.5)\n",
        "    legend(\"topleft\", legend=c(\"MCP + 25 km\",\"MCP\",\"Pres (usadas)\",\"Outliers MCP\"),\n",
        "           lwd=c(2,2,NA,NA), lty=c(1,2,NA,NA), pch=c(NA,NA,20,4),\n",
        "           col=c(\"orange\",\"red\",\"blue\",\"darkorange\"), bty=\"n\")\n",
        "    invisible(dev.off())\n",
        "    sf::st_write(M_poly, file.path(out_dir, \"area_M.gpkg\"), delete_dsn=TRUE, quiet=TRUE)\n",
        "\n",
        "    env_M_t   <- terra::mask(terra::crop(env_full, terra::vect(M_poly)), terra::vect(M_poly))\n",
        "    vals_pres <- terra::extract(env_M_t, as.matrix(Mres$pres_trim))\n",
        "    keep      <- complete.cases(vals_pres)\n",
        "    pres_use  <- Mres$pres_trim[keep, , drop=FALSE]\n",
        "    if (nrow(pres_use) <= 10) { writeLines(\"<=10 presencias válidas (NA en predictores).\", con=file.path(out_dir,\"ERROR.txt\")); return(NULL) }\n",
        "\n",
        "    tmp_tif  <- file.path(out_dir, \"env_M.tif\")\n",
        "    terra::writeRaster(env_M_t, tmp_tif, overwrite=TRUE)\n",
        "    env_M_rs <- raster::stack(tmp_tif)\n",
        "\n",
        "    # Tuning\n",
        "    tuning_rows <- list()\n",
        "    for (FC in FC_SET) for (RM in RM_SET) {\n",
        "      cv_dir <- file.path(out_dir, sprintf(\"maxent_cv_FC-%s_RM-%s\", FC, RM))\n",
        "      dir.create(cv_dir, showWarnings = FALSE)\n",
        "      args_cv <- c(\"outputformat=logistic\",\n",
        "                   paste0(\"replicates=\", REPS), \"replicatetype=crossvalidate\", \"randomtestpoints=0\",\n",
        "                   fc_to_args(FC), paste0(\"betamultiplier=\", RM))\n",
        "      invisible(dismo::maxent(x=env_M_rs, p=as.matrix(pres_use[,c(\"lon\",\"lat\")]), path=cv_dir, args=args_cv))\n",
        "      mx_csv <- file.path(cv_dir, \"maxentResults.csv\"); if (!file.exists(mx_csv)) next\n",
        "      mx <- suppressWarnings(readr::read_csv(mx_csv, show_col_types = FALSE,\n",
        "                                             locale=readr::locale(decimal_mark=\".\", grouping_mark=\",\")))\n",
        "      names(mx) <- normalize_names(names(mx))\n",
        "      spec_col <- names(mx)[1]; avg_row <- which(grepl(\"\\\\(average\\\\)\\\\s*$\", tolower(mx[[spec_col]])))\n",
        "      if (!length(avg_row)) next\n",
        "      col_tr <- getcol_exact(mx,\"Training AUC\"); col_ts <- getcol_exact(mx,\"Test AUC\")\n",
        "      thr_labels <- c(\"Maximum test sensitivity plus specificity Logistic threshold\",\n",
        "                      \"Equal test sensitivity and specificity Logistic threshold\",\n",
        "                      \"Maximum training sensitivity plus specificity Logistic threshold\",\n",
        "                      \"Equal training sensitivity and specificity Logistic threshold\")\n",
        "      col_thr <- character(0); for (lbl in thr_labels){ cnd<-getcol_exact(mx,lbl); if (length(cnd)){col_thr<-cnd; break}}\n",
        "      omit_labels <- c(\"Maximum test sensitivity plus specificity test omission\",\n",
        "                       \"Equal test sensitivity and specificity test omission\")\n",
        "      col_omit <- character(0); for (lbl in omit_labels){ cnd<-getcol_exact(mx,lbl); if (length(cnd)){col_omit<-cnd; break}}\n",
        "      tuning_rows[[length(tuning_rows)+1]] <- data.frame(\n",
        "        species=sp, FC=FC, RM=RM,\n",
        "        AUC_train_mean = if (length(col_tr)) round(numify(mx[[col_tr]][avg_row]),5) else NA,\n",
        "        AUC_test_mean  = if (length(col_ts)) round(numify(mx[[col_ts]][avg_row]),5) else NA,\n",
        "        thr_logistic   = if (length(col_thr)) round(numify(mx[[col_thr]][avg_row]),5) else NA,\n",
        "        test_omission  = if (length(col_omit)) round(numify(mx[[col_omit]][avg_row]),5) else NA,\n",
        "        stringsAsFactors=FALSE\n",
        "      )\n",
        "    }\n",
        "    tuning_df <- if (length(tuning_rows)) dplyr::bind_rows(tuning_rows) else NULL\n",
        "    if (is.null(tuning_df) || nrow(tuning_df)==0) { writeLines(\"Tuning vacío.\", con=file.path(out_dir,\"ERROR.txt\")); return(NULL) }\n",
        "    readr::write_csv(tuning_df, file.path(out_dir, \"tuning_summary.csv\"))\n",
        "\n",
        "    ord <- with(tuning_df, order(-AUC_test_mean, ifelse(is.na(test_omission), Inf, test_omission), -RM))\n",
        "    best <- tuning_df[ord[1], , drop=FALSE]\n",
        "    best_FC <- best$FC[1]; best_RM <- best$RM[1]; best_thr <- best$thr_logistic[1]; best_auc_ts <- best$AUC_test_mean[1]\n",
        "    writeLines(sprintf(\"Best combo: FC=%s RM=%s | Test AUC=%.3f | thr=%.4f\",\n",
        "                       best_FC, best_RM, best_auc_ts, best_thr),\n",
        "               con = file.path(out_dir, \"best_FC_RM.txt\"))\n",
        "    if (is.na(best_thr)) { writeLines(\"Sin umbral MSS (TEST) para la combinación ganadora.\", con=file.path(out_dir,\"ERROR.txt\")); return(NULL) }\n",
        "\n",
        "    args_final <- c(\"outputformat=logistic\", fc_to_args(best_FC), paste0(\"betamultiplier=\", best_RM))\n",
        "    final_dir  <- file.path(out_dir, \"maxent_final\"); dir.create(final_dir, showWarnings = FALSE)\n",
        "    me_final   <- dismo::maxent(x=env_M_rs, p=as.matrix(pres_use[,c(\"lon\",\"lat\")]), path=final_dir, args=args_final)\n",
        "\n",
        "    r_cont  <- raster::predict(env_M_rs, me_final, progress=\"text\")\n",
        "    r_bin01 <- raster::calc(r_cont, function(x) as.integer(x >= best_thr))\n",
        "    stem <- file.path(out_dir, gsub(\" \", \"_\", sp))\n",
        "    raster::writeRaster(r_cont,  paste0(stem,\"_present_continuous.tif\"),\n",
        "                        overwrite=TRUE, datatype=\"FLT4S\", options=c(\"COMPRESS=LZW\"))\n",
        "    raster::writeRaster(r_bin01, paste0(stem,\"_present_binary_spec_sens.tif\"),\n",
        "                        overwrite=TRUE, datatype=\"INT1U\", options=c(\"COMPRESS=LZW\"))\n",
        "\n",
        "    km2_pres <- sum(raster::values(raster::area(r_bin01)) * (raster::values(r_bin01)==1), na.rm=TRUE)\n",
        "\n",
        "    fut_cols <- list()\n",
        "    if (length(FUTURES)){\n",
        "      for (sc in FUTURES){\n",
        "        tag <- sc$tag; fut_path <- sc$tif\n",
        "        km2_fut <- NA_real_; delta_pct <- NA_real_\n",
        "        try({\n",
        "          env_F0_t <- terra::rast(fut_path)\n",
        "          if (terra::nlyr(env_F0_t) != terra::nlyr(env_full))\n",
        "            stop(sprintf(\"Capas futuras (%d) != presentes (%d)\", terra::nlyr(env_F0_t), terra::nlyr(env_full)))\n",
        "          names(env_F0_t) <- names(env_full)\n",
        "          env_F_t  <- terra::mask(terra::crop(env_F0_t, terra::vect(M_poly)), terra::vect(M_poly))\n",
        "          tmpF     <- file.path(out_dir, paste0(\"env_F_\", tag, \".tif\"))\n",
        "          terra::writeRaster(env_F_t, tmpF, overwrite=TRUE)\n",
        "          env_F_rs <- raster::stack(tmpF)\n",
        "\n",
        "          r_cont_fut <- raster::predict(env_F_rs, me_final, progress=\"text\",\n",
        "                                        args=c(\"outputformat=logistic\",\"extrapolate=false\",\"doclamp=false\"))\n",
        "          r_bin_fut  <- raster::calc(r_cont_fut, function(x) as.integer(x >= best_thr))\n",
        "\n",
        "          raster::writeRaster(r_cont_fut, paste0(stem,\"_future_continuous_\",tag,\".tif\"),\n",
        "                              overwrite=TRUE, datatype=\"FLT4S\", options=c(\"COMPRESS=LZW\"))\n",
        "          raster::writeRaster(r_bin_fut,  paste0(stem,\"_future_binary_spec_sens_\",tag,\".tif\"),\n",
        "                              overwrite=TRUE, datatype=\"INT1U\", options=c(\"COMPRESS=LZW\"))\n",
        "\n",
        "          km2_fut   <- sum(raster::values(raster::area(r_bin_fut)) * (raster::values(r_bin_fut)==1), na.rm=TRUE)\n",
        "          delta_pct <- if (is.finite(km2_pres) && km2_pres>0) 100*(km2_fut - km2_pres)/km2_pres else NA_real_\n",
        "        })\n",
        "        fut_cols[[paste0(\"area_km2_future_\", tag)]] <- round(km2_fut, 2)\n",
        "        fut_cols[[paste0(\"delta_pct_\", tag)]]       <- round(delta_pct, 2)\n",
        "      }\n",
        "    }\n",
        "\n",
        "    stats_df <- data.frame(\n",
        "      species             = sp,\n",
        "      n_pres_total        = nrow(pres_all),\n",
        "      n_pres_used_in_M    = nrow(pres_use),\n",
        "      n_predictors        = raster::nlayers(env_M_rs),\n",
        "      predictors          = paste(names(env_M_rs), collapse=\";\"),\n",
        "      area_M_km2          = round(area_km2, 2),\n",
        "      area_km2_present    = round(km2_pres, 2),\n",
        "      replicates          = 5,\n",
        "      replicatetype       = \"crossvalidate\",\n",
        "      best_FC             = best_FC,\n",
        "      best_RM             = best_RM,\n",
        "      AUC_test_mean       = round(best_auc_ts, 4),\n",
        "      threshold_TEST_MSS  = round(best_thr, 4),\n",
        "      stringsAsFactors    = FALSE\n",
        "    )\n",
        "    if (length(fut_cols)) stats_df <- cbind(stats_df, as.data.frame(fut_cols, check.names = FALSE))\n",
        "    readr::write_csv(stats_df, file.path(out_dir, \"model_stats.csv\"))\n",
        "    stats_df\n",
        "  }\n",
        "\n",
        "  all_rows <- list()\n",
        "  for (sp in species_all) {\n",
        "    cat(\"\\nSTEP3 ▶\", sp, \"\\n\")\n",
        "    res <- try(run_one_species(sp), silent = TRUE)\n",
        "    if (inherits(res, \"try-error\") || is.null(res)) {\n",
        "      out_dir <- file.path(MODELS_DIR, safe_dir(sp))\n",
        "      writeLines(as.character(attr(res,\"condition\")), con = file.path(out_dir, \"ERROR.txt\"))\n",
        "      message(\"ERROR en especie: \", sp)\n",
        "    } else {\n",
        "      all_rows[[length(all_rows)+1]] <- res\n",
        "    }\n",
        "    gc()\n",
        "  }\n",
        "  if (length(all_rows)) {\n",
        "    all_df <- dplyr::bind_rows(all_rows)\n",
        "    readr::write_csv(all_df, file.path(MODELS_DIR, \"all_species_summary.csv\"))\n",
        "    message(\"STEP3 ✅ Resumen global -> all_species_summary.csv\")\n",
        "  } else {\n",
        "    message(\"STEP3 ⚠ Sin modelos exitosos; revisa ERROR.txt por especie\")\n",
        "  }\n",
        "} else {\n",
        "  cat(\"STEP3 ⏭ Saltado (se asume MODELS_DIR con modelos listos)\\n\")\n",
        "}\n",
        "\n",
        "# =========================================================\n",
        "# STEP 4 — Mapas de riqueza (presente + futuros)\n",
        "# =========================================================\n",
        "safe_name <- function(x) {\n",
        "  x %>%\n",
        "    gsub(\"[^A-Za-z0-9_\\\\-]+\", \"_\", .) %>%\n",
        "    gsub(\"_+\", \"_\", .) %>%\n",
        "    gsub(\"^_|_$\", \"\", .)\n",
        "}\n",
        "if (RUN_STEP_4_RIQUEZA) {\n",
        "  base_dir <- MODELS_DIR\n",
        "  PAT_PRESENT <- \"_present_binary_spec_sens\\\\.tif$\"\n",
        "  FUTS <- lapply(FUTURES, function(z) list(tag=z$tag, pat=paste0(\"_future_binary_spec_sens_\", z$tag, \"\\\\.tif$\")))\n",
        "  out_dir <- RICH_OUT_DIR; dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)\n",
        "\n",
        "  species_dirs_all <- list.dirs(base_dir, recursive = FALSE, full.names = TRUE)\n",
        "  species_dirs     <- species_dirs_all[species_dirs_all != out_dir & dir.exists(species_dirs_all)]\n",
        "  find_any_present <- function(sp_dir) {\n",
        "    fs <- list.files(sp_dir, pattern = PAT_PRESENT, full.names = TRUE, ignore.case = TRUE)\n",
        "    if (length(fs)) fs[1] else NA_character_\n",
        "  }\n",
        "  present_files <- lapply(species_dirs, find_any_present)\n",
        "  names(present_files) <- basename(species_dirs)\n",
        "  present_files <- present_files[!is.na(unlist(present_files))]\n",
        "  auto_assert(length(present_files)>0, paste(\"No se encontraron TIF de presente con el patrón:\", PAT_PRESENT))\n",
        "\n",
        "  first_present <- try(terra::rast(present_files[[1]]), silent = TRUE)\n",
        "  auto_assert(!inherits(first_present,\"try-error\"), \"No pude abrir el primer raster presente.\")\n",
        "  if (is.na(terra::crs(first_present))) terra::crs(first_present) <- \"epsg:4326\"\n",
        "\n",
        "  ext_union <- terra::ext(first_present)\n",
        "  for (p in present_files) {\n",
        "    r <- try(terra::rast(p), silent = TRUE); if (inherits(r, \"try-error\")) next\n",
        "    if (!identical(terra::crs(r), terra::crs(first_present))) {\n",
        "      r <- try(terra::project(r, first_present, method = \"near\"), silent = TRUE); if (inherits(r, \"try-error\")) next\n",
        "    }\n",
        "    ext_union <- terra::union(ext_union, terra::ext(r))\n",
        "  }\n",
        "  canvas <- terra::rast(extent = ext_union, resolution = terra::res(first_present), crs = terra::crs(first_present))\n",
        "\n",
        "  present_layers <- list(); band_index_present <- list()\n",
        "  for (sp in names(present_files)) {\n",
        "    f <- present_files[[sp]]\n",
        "    r <- try(terra::rast(f), silent = TRUE); if (inherits(r,\"try-error\")) next\n",
        "    if (!identical(terra::crs(r), terra::crs(canvas))) {\n",
        "      r <- try(terra::project(r, canvas, method = \"near\"), silent = TRUE); if (inherits(r,\"try-error\")) next\n",
        "    }\n",
        "    rA <- terra::resample(r, canvas, method = \"near\"); rA <- rA >= 1; rA <- terra::ifel(is.na(rA), 0, rA)\n",
        "    nm <- safe_name(sp); names(rA) <- nm\n",
        "    present_layers[[length(present_layers)+1]] <- rA\n",
        "    band_index_present[[length(band_index_present)+1]] <- data.frame(band=length(present_layers), species=sp, filename=f)\n",
        "  }\n",
        "  auto_assert(length(present_layers)>0, \"No quedaron capas presentes apiladas.\")\n",
        "  present_stack <- if (length(present_layers)==1) present_layers[[1]] else do.call(c, present_layers)\n",
        "  present_rich  <- sum(present_stack); names(present_rich) <- \"richness\"\n",
        "  present_final <- c(present_stack, present_rich)\n",
        "  present_out_tif <- file.path(out_dir, \"richness_present_stack.tif\")\n",
        "  terra::writeRaster(present_final, present_out_tif, overwrite=TRUE,\n",
        "                     wopt=list(datatype=\"INT2U\", gdal=c(\"COMPRESS=LZW\",\"BIGTIFF=IF_SAFER\")))\n",
        "  present_bands_df <- dplyr::bind_rows(band_index_present)\n",
        "  present_bands_df <- rbind(present_bands_df,\n",
        "                            data.frame(band=nlyr(present_final), species=\"richness\", filename=present_out_tif))\n",
        "  readr::write_csv(present_bands_df, file.path(out_dir, \"band_index_present.csv\"))\n",
        "  cat(\"STEP4 ✅ Stack presente -> \", present_out_tif, \"\\n\", sep=\"\")\n",
        "\n",
        "  present_species_stack <- present_final[[1:(nlyr(present_final)-1)]]\n",
        "\n",
        "  for (sc in FUTS) {\n",
        "    tag <- sc$tag; pat <- sc$pat\n",
        "    cat(\"\\nSTEP4 ▶ Escenario futuro:\", tag, \"\\n\")\n",
        "    future_files <- list()\n",
        "    for (spdir in species_dirs) {\n",
        "      files <- list.files(spdir, pattern = pat, full.names = TRUE, ignore.case = TRUE)\n",
        "      if (length(files)) future_files[[basename(spdir)]] <- files[1]\n",
        "    }\n",
        "    if (!length(future_files)) { message(\"⚠ Sin archivos futuros para patrón: \", pat); next }\n",
        "\n",
        "    fut_layers <- list(); band_index_future <- list()\n",
        "    for (sp in names(future_files)) {\n",
        "      f <- future_files[[sp]]\n",
        "      r <- try(terra::rast(f), silent = TRUE); if (inherits(r,\"try-error\")) next\n",
        "      if (!identical(terra::crs(r), terra::crs(canvas))) {\n",
        "        r <- try(terra::project(r, canvas, method = \"near\"), silent = TRUE); if (inherits(r,\"try-error\")) next\n",
        "      }\n",
        "      rA <- terra::resample(r, canvas, method = \"near\"); rA <- rA >= 1; rA <- terra::ifel(is.na(rA), 0, rA)\n",
        "      nm <- safe_name(sp); names(rA) <- nm\n",
        "      fut_layers[[length(fut_layers)+1]] <- rA\n",
        "      band_index_future[[length(band_index_future)+1]] <- data.frame(band=length(fut_layers), species=sp, filename=f)\n",
        "    }\n",
        "    if (!length(fut_layers)) { message(\"⚠ No quedaron capas futuras apiladas para \", tag); next }\n",
        "    future_stack <- if (length(fut_layers)==1) fut_layers[[1]] else do.call(c, fut_layers)\n",
        "    future_rich  <- sum(future_stack); names(future_rich) <- \"richness\"\n",
        "    future_final <- c(future_stack, future_rich)\n",
        "    fut_out_tif  <- file.path(out_dir, paste0(\"richness_future_stack_\", tag, \".tif\"))\n",
        "    terra::writeRaster(future_final, fut_out_tif, overwrite=TRUE,\n",
        "                       wopt=list(datatype=\"INT2U\", gdal=c(\"COMPRESS=LZW\",\"BIGTIFF=IF_SAFER\")))\n",
        "    future_bands_df <- dplyr::bind_rows(band_index_future)\n",
        "    future_bands_df <- rbind(future_bands_df,\n",
        "                             data.frame(band=nlyr(future_final), species=\"richness\", filename=fut_out_tif))\n",
        "    readr::write_csv(future_bands_df, file.path(out_dir, paste0(\"band_index_future_\", tag, \".csv\")))\n",
        "    cat(\"STEP4 ✅ Futuro (\", tag, \") -> \", fut_out_tif, \"\\n\", sep=\"\")\n",
        "\n",
        "    # Cambios de riqueza (especies comunes)\n",
        "    future_species_stack <- future_final[[1:(nlyr(future_final)-1)]]\n",
        "    common_sp <- intersect(names(present_species_stack), names(future_species_stack))\n",
        "    if (length(common_sp) >= 1) {\n",
        "      P_common <- present_species_stack[[common_sp]]\n",
        "      F_common <- future_species_stack[[common_sp]]\n",
        "      rich_P_common <- sum(P_common); rich_F_common <- sum(F_common)\n",
        "      rich_delta_abs <- rich_F_common - rich_P_common\n",
        "      names(rich_delta_abs) <- paste0(\"richness_delta_abs_\", tag)\n",
        "      rich_delta_pct <- (rich_F_common - rich_P_common) * 100\n",
        "      rich_delta_pct <- rich_delta_pct / terra::ifel(rich_P_common > 0, rich_P_common, NA)\n",
        "      names(rich_delta_pct) <- paste0(\"richness_delta_pct_\", tag)\n",
        "      gain_stack <- (F_common > 0) & (P_common == 0)\n",
        "      loss_stack <- (P_common > 0) & (F_common == 0)\n",
        "      gain_count <- sum(gain_stack); names(gain_count) <- paste0(\"richness_gain_only_\", tag)\n",
        "      loss_count <- sum(loss_stack); names(loss_count) <- paste0(\"richness_loss_only_\", tag)\n",
        "      turnover <- gain_count + loss_count; names(turnover) <- paste0(\"richness_turnover_\", tag)\n",
        "\n",
        "      terra::writeRaster(rich_delta_abs, file.path(out_dir, paste0(\"richness_change_abs_common_\", tag, \".tif\")),\n",
        "                         overwrite=TRUE, wopt=list(datatype=\"INT2S\", gdal=c(\"COMPRESS=LZW\",\"BIGTIFF=IF_SAFER\")))\n",
        "      terra::writeRaster(rich_delta_pct, file.path(out_dir, paste0(\"richness_change_pct_common_\", tag, \".tif\")),\n",
        "                         overwrite=TRUE, wopt=list(datatype=\"FLT4S\", gdal=c(\"COMPRESS=LZW\",\"BIGTIFF=IF_SAFER\")))\n",
        "      terra::writeRaster(gain_count, file.path(out_dir, paste0(\"richness_gain_only_common_\", tag, \".tif\")),\n",
        "                         overwrite=TRUE, wopt=list(datatype=\"INT2U\", gdal=c(\"COMPRESS=LZW\",\"BIGTIFF=IF_SAFER\")))\n",
        "      terra::writeRaster(loss_count, file.path(out_dir, paste0(\"richness_loss_only_common_\", tag, \".tif\")),\n",
        "                         overwrite=TRUE, wopt=list(datatype=\"INT2U\", gdal=c(\"COMPRESS=LZW\",\"BIGTIFF=IF_SAFER\")))\n",
        "      terra::writeRaster(turnover, file.path(out_dir, paste0(\"richness_turnover_common_\", tag, \".tif\")),\n",
        "                         overwrite=TRUE, wopt=list(datatype=\"INT2U\", gdal=c(\"COMPRESS=LZW\",\"BIGTIFF=IF_SAFER\")))\n",
        "      readr::write_csv(data.frame(species = common_sp),\n",
        "                       file.path(out_dir, paste0(\"richness_change_common_species_\", tag, \".csv\")))\n",
        "      cat(\"STEP4 ✓ Cambio de riqueza (\", tag, \") guardado.\\n\", sep=\"\")\n",
        "    } else {\n",
        "      message(\"STEP4 ⚠ Sin especies comunes entre presente y futuro para \", tag)\n",
        "    }\n",
        "  }\n",
        "} else {\n",
        "  cat(\"STEP4 ⏭ Saltado\\n\")\n",
        "}\n",
        "\n",
        "cat(\"\\n✔ Flujo SDM completo (master) finalizado.\\n\")\n"
      ]
    }
  ]
}