{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNVegouar/o3ofeEAYcTZb9",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/hmg8906/CienciaDatosCN/blob/TFM/postprocesing.R\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "IDpvGJFRHJA_"
      },
      "outputs": [],
      "source": [
        "# ============================================================\n",
        "# POSTPROCESO Y ANÁLISIS INTEGRADO\n",
        "# - Mapas comparativos por especie (2×2: binario/continuo, 2025/2040)\n",
        "# - Mapas de riqueza (1×3: 2025 | 2040 | Δ)\n",
        "# - Estadística zonal por ecorregión (resúmenes, boxplots, pruebas pareadas)\n",
        "# - Riesgo de deforestación: mapa, proyección acumulada y áreas por ecorregión\n",
        "# Autor: [Tu nombre]\n",
        "# Fecha: [YYYY-MM-DD]\n",
        "# Notas:\n",
        "#   * Se mantienen rutas absolutas originales.\n",
        "#   * No se remuestrean rásteres salvo donde es estrictamente necesario\n",
        "#     (alinear 2040 a la rejilla 2025 o similar).\n",
        "#   * Se eliminaron bloques duplicados y se homogeneizó la documentación.\n",
        "# ============================================================\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# A) ESPECIE EJEMPLO — Plecturocebus caquetensis (Panel 2×2)\n",
        "#    Arriba: mapas binarios (gris=no apto, negro=apto)\n",
        "#    Abajo: mapas continuos (viridis)\n",
        "#    Izq: 2025 | Der: 2040\n",
        "#    Ecorregiones WWF (Colombia) en contorno\n",
        "# ============================================================\n",
        "\n",
        "# Paquetes\n",
        "pkgs <- c(\"terra\",\"sf\",\"ggplot2\",\"tidyterra\",\"patchwork\")\n",
        "new  <- pkgs[!pkgs %in% installed.packages()[,\"Package\"]]\n",
        "if (length(new)) install.packages(new, dependencies = TRUE)\n",
        "library(terra); library(sf); library(ggplot2); library(tidyterra); library(patchwork)\n",
        "\n",
        "# Rutas\n",
        "f_bin_2025  <- \"C:/Users/henry.garcia/Desktop/PC_bin_2025.tif\"\n",
        "f_bin_2040  <- \"C:/Users/henry.garcia/Desktop/PC_bin_2040.tif\"\n",
        "f_cont_2025 <- \"C:/Users/henry.garcia/Desktop/PC_cont_2025.tif\"\n",
        "f_cont_2040 <- \"C:/Users/henry.garcia/Desktop/PC_cont_2040.tif\"\n",
        "eco_shp     <- \"C:/Users/henry.garcia/Desktop/Primates/ecoregions/wwf_terr_ecos_col.shp\"\n",
        "outfile     <- \"C:/Users/henry.garcia/Desktop/PCaquetensis_2x2_eco_2025_2040.png\"\n",
        "\n",
        "for (p in c(f_bin_2025,f_bin_2040,f_cont_2025,f_cont_2040)) if (!file.exists(p)) stop(\"No existe: \", p)\n",
        "if (!file.exists(eco_shp)) stop(\"No existe shapefile: \", eco_shp)\n",
        "\n",
        "# Leer rásteres (SIN alinear ni remuestrear)\n",
        "r_bin_2025  <- rast(f_bin_2025)\n",
        "r_bin_2040  <- rast(f_bin_2040)\n",
        "r_cont_2025 <- rast(f_cont_2025)\n",
        "r_cont_2040 <- rast(f_cont_2040)\n",
        "\n",
        "# Ecorregiones base\n",
        "eco0 <- st_read(eco_shp, quiet = TRUE) |> st_make_valid()\n",
        "\n",
        "# Adaptar ecorregiones al CRS/extent del ráster (sin modificar el ráster)\n",
        "prep_eco_for <- function(r){\n",
        "  eco <- suppressWarnings(st_transform(eco0, crs = st_crs(terra::crs(r, proj = TRUE))))\n",
        "  sv  <- terra::vect(eco)\n",
        "  svc <- tryCatch(terra::crop(sv, r), error = function(e) sv)\n",
        "  st_as_sf(svc)\n",
        "}\n",
        "\n",
        "# Binarios a factor 0/1 con etiquetas\n",
        "to_factor01 <- function(r){\n",
        "  r01 <- terra::ifel(r > 0, 1, 0)  # >0 -> 1 (Apto); <=0 -> 0 (No apto); NA preserva\n",
        "  rf  <- as.factor(r01)\n",
        "  lv  <- data.frame(ID = c(0, 1), label = c(\"No apto\", \"Apto\"))\n",
        "  if (is.list(levels(rf))) levels(rf) <- list(lv) else levels(rf) <- lv\n",
        "  rf\n",
        "}\n",
        "rb25f <- to_factor01(r_bin_2025)\n",
        "rb40f <- to_factor01(r_bin_2040)\n",
        "\n",
        "# Tema\n",
        "theme_map <- theme_void(base_size = 11) +\n",
        "  theme(plot.title = element_text(face=\"bold\", margin=margin(b=3)),\n",
        "        legend.title = element_text(),\n",
        "        legend.position = \"right\")\n",
        "\n",
        "# BINARIO 2025 (arriba-izq)\n",
        "eco_b25 <- prep_eco_for(rb25f)\n",
        "p_bin_2025 <- ggplot() +\n",
        "  geom_spatraster(data = rb25f, na.rm = TRUE) +\n",
        "  scale_fill_manual(\n",
        "    values = c(\"No apto\" = \"grey85\", \"Apto\" = \"black\"),\n",
        "    name   = \"Binario\",\n",
        "    breaks = c(\"No apto\",\"Apto\"),\n",
        "    limits = c(\"No apto\",\"Apto\"),\n",
        "    drop   = FALSE\n",
        "  ) +\n",
        "  geom_sf(data = eco_b25, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_sf(expand = FALSE, datum = NA) +\n",
        "  labs(title = \"Binario 2025\") + theme_map\n",
        "\n",
        "# BINARIO 2040 (arriba-der)\n",
        "eco_b40 <- prep_eco_for(rb40f)\n",
        "p_bin_2040 <- ggplot() +\n",
        "  geom_spatraster(data = rb40f, na.rm = TRUE) +\n",
        "  scale_fill_manual(\n",
        "    values = c(\"No apto\" = \"grey85\", \"Apto\" = \"black\"),\n",
        "    name   = \"Binario\",\n",
        "    breaks = c(\"No apto\",\"Apto\"),\n",
        "    limits = c(\"No apto\",\"Apto\"),\n",
        "    drop   = FALSE\n",
        "  ) +\n",
        "  geom_sf(data = eco_b40, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_sf(expand = FALSE, datum = NA) +\n",
        "  labs(title = \"Binario 2040 (SSP585)\") + theme_map\n",
        "\n",
        "# CONTINUO 2025 (abajo-izq)\n",
        "eco_c25 <- prep_eco_for(r_cont_2025)\n",
        "p_cont_2025 <- ggplot() +\n",
        "  geom_spatraster(data = r_cont_2025, na.rm = TRUE) +\n",
        "  scale_fill_viridis_c(name = \"Idoneidad\", na.value = NA) +\n",
        "  geom_sf(data = eco_c25, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_sf(expand = FALSE, datum = NA) +\n",
        "  labs(title = \"Continuo 2025\") + theme_map\n",
        "\n",
        "# CONTINUO 2040 (abajo-der)\n",
        "eco_c40 <- prep_eco_for(r_cont_2040)\n",
        "p_cont_2040 <- ggplot() +\n",
        "  geom_spatraster(data = r_cont_2040, na.rm = TRUE) +\n",
        "  scale_fill_viridis_c(name = \"Idoneidad\", na.value = NA) +\n",
        "  geom_sf(data = eco_c40, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_sf(expand = FALSE, datum = NA) +\n",
        "  labs(title = \"Continuo 2040 (SSP585)\") + theme_map\n",
        "\n",
        "# Panel 2×2 y guardado\n",
        "panel <- (p_bin_2025 + p_bin_2040) /\n",
        "  (p_cont_2025 + p_cont_2040) +\n",
        "  plot_annotation(\n",
        "    title = \"Plecturocebus caquetensis — 2025 vs 2040\",\n",
        "    subtitle = \"Arriba: binarios; Abajo: continuos — contorno: ecorregiones WWF (Colombia)\",\n",
        "    theme = theme(plot.title = element_text(face=\"bold\", size=14),\n",
        "                  plot.subtitle = element_text(size=11))\n",
        "  )\n",
        "ggsave(outfile, panel, width = 12, height = 10, dpi = 300)\n",
        "message(\"✅ Figura guardada en: \", outfile)\n",
        "\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# B) RIQUEZA DE PRIMATES — Panel 1×3 (2025 | 2040 | Δ=2040−2025)\n",
        "#    - Alinea 2040 a la rejilla de 2025 (baseline)\n",
        "#    - Ecorregiones en contorno\n",
        "# ============================================================\n",
        "\n",
        "pkgs <- c(\"terra\",\"sf\",\"ggplot2\",\"tidyterra\",\"patchwork\")\n",
        "new  <- pkgs[!pkgs %in% installed.packages()[,\"Package\"]]\n",
        "if (length(new)) install.packages(new, dependencies = TRUE)\n",
        "library(terra); library(sf); library(ggplot2); library(tidyterra); library(patchwork)\n",
        "\n",
        "# Rutas\n",
        "f_rich_2025 <- \"C:/Users/henry.garcia/Desktop/Primates/models_maxent_ALL_ecoregM/0.richness_maps/riqueza_2025_col.tif\"\n",
        "f_rich_2040 <- \"C:/Users/henry.garcia/Desktop/Primates/models_maxent_ALL_ecoregM/0.richness_maps/riqueza_2040_col.tif\"\n",
        "f_rich_delta<- \"C:/Users/henry.garcia/Desktop/Primates/models_maxent_ALL_ecoregM/0.richness_maps/riqueza_dellta_col.tif\"  # si existe, se usa\n",
        "eco_shp     <- \"C:/Users/henry.garcia/Desktop/Primates/ecoregions/wwf_terr_ecos_col.shp\"\n",
        "\n",
        "for (p in c(f_rich_2025,f_rich_2040)) if (!file.exists(p)) stop(\"No existe: \", p)\n",
        "if (!file.exists(eco_shp)) stop(\"No existe shapefile: \", eco_shp)\n",
        "\n",
        "# Leer\n",
        "r25    <- rast(f_rich_2025)\n",
        "r40raw <- rast(f_rich_2040)\n",
        "\n",
        "# Alinear 2040 a 2025\n",
        "r40 <- if (!compareGeom(r25, r40raw, stopOnError = FALSE)) {\n",
        "  project(r40raw, r25, method = \"bilinear\")\n",
        "} else r40raw\n",
        "\n",
        "# Delta (usar archivo si existe; si no, calcular)\n",
        "if (file.exists(f_rich_delta)) {\n",
        "  rD_raw <- rast(f_rich_delta)\n",
        "  rD <- if (!compareGeom(r25, rD_raw, stopOnError = FALSE)) {\n",
        "    project(rD_raw, r25, method = \"bilinear\")\n",
        "  } else rD_raw\n",
        "} else {\n",
        "  rD <- r40 - r25\n",
        "}\n",
        "\n",
        "# Ecorregiones a cada ráster\n",
        "eco0 <- st_read(eco_shp, quiet = TRUE) |> st_make_valid()\n",
        "prep_eco_for <- function(r){\n",
        "  rcrs <- crs(r, proj = TRUE)\n",
        "  eco  <- if (nzchar(rcrs)) suppressWarnings(st_transform(eco0, st_crs(rcrs))) else eco0\n",
        "  sv   <- vect(eco); svc <- tryCatch(crop(sv, r), error = function(e) sv)\n",
        "  st_as_sf(svc)\n",
        "}\n",
        "\n",
        "# Escalas\n",
        "vmax <- max(as.numeric(global(r25, \"max\", na.rm = TRUE)),\n",
        "            as.numeric(global(r40, \"max\", na.rm = TRUE)), na.rm = TRUE)\n",
        "dmin <- as.numeric(global(rD, \"min\", na.rm = TRUE))\n",
        "dmax <- as.numeric(global(rD, \"max\", na.rm = TRUE))\n",
        "\n",
        "theme_map <- theme_void(base_size = 11) +\n",
        "  theme(plot.title = element_text(face=\"bold\", margin=margin(b=3)),\n",
        "        legend.title = element_text(),\n",
        "        legend.position = \"right\")\n",
        "coord_map <- coord_sf(expand = FALSE, datum = NA)\n",
        "\n",
        "# Mapas y panel\n",
        "eco25 <- prep_eco_for(r25)\n",
        "p25 <- ggplot() +\n",
        "  geom_spatraster(data = r25, na.rm = TRUE) +\n",
        "  scale_fill_viridis_c(name = \"Riqueza\", limits = c(0, vmax), oob = scales::squish) +\n",
        "  geom_sf(data = eco25, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_map + labs(title = \"Riqueza 2025\") + theme_map\n",
        "\n",
        "eco40 <- prep_eco_for(r40)\n",
        "p40 <- ggplot() +\n",
        "  geom_spatraster(data = r40, na.rm = TRUE) +\n",
        "  scale_fill_viridis_c(name = \"Riqueza\", limits = c(0, vmax), oob = scales::squish) +\n",
        "  geom_sf(data = eco40, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_map + labs(title = \"Riqueza 2040 (SSP585)\") + theme_map\n",
        "\n",
        "ecoD <- prep_eco_for(rD)\n",
        "pD <- ggplot() +\n",
        "  geom_spatraster(data = rD, na.rm = TRUE) +\n",
        "  scale_fill_viridis_c(name = \"Δ riqueza (2040 − 2025)\",\n",
        "                       limits = c(dmin, dmax), oob = scales::squish) +\n",
        "  geom_sf(data = ecoD, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_map + labs(title = \"Δ Riqueza (2040 − 2025)\") + theme_map\n",
        "\n",
        "panel <- p25 + p40 + pD +\n",
        "  plot_annotation(\n",
        "    title    = \"Riqueza de primates — 2025 | 2040 | Δ 2040−2025 (viridis)\",\n",
        "    subtitle = \"Ecorregiones WWF (Colombia) en contorno\",\n",
        "    theme = theme(plot.title = element_text(face=\"bold\", size=14),\n",
        "                  plot.subtitle = element_text(size = 11))\n",
        "  )\n",
        "\n",
        "outfile <- \"C:/Users/henry.garcia/Desktop/richness_1x3_viridis_2025_2040_delta.png\"\n",
        "ggsave(outfile, panel, width = 16, height = 6, dpi = 300)\n",
        "message(\"✅ Figura guardada en: \", outfile)\n",
        "\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# C) RIQUEZA PROMEDIO POR ECORREGIÓN Y BOXPLOTS 2025 vs 2040\n",
        "#    - Estadística zonal (media) + n celdas válidas\n",
        "#    - Boxplots por periodo y (opcional) Δ por ecorregión\n",
        "# ============================================================\n",
        "\n",
        "pkgs <- c(\"terra\",\"sf\",\"dplyr\",\"ggplot2\",\"tidyr\",\"readr\")\n",
        "new  <- setdiff(pkgs, rownames(installed.packages()))\n",
        "if (length(new)) install.packages(new, dependencies = TRUE)\n",
        "library(terra); library(sf); library(dplyr); library(ggplot2); library(tidyr); library(readr)\n",
        "\n",
        "# Rutas\n",
        "f_rich_2025 <- \"C:/Users/henry.garcia/Desktop/Primates/models_maxent_ALL_ecoregM/0.richness_maps/riqueza_2025_col.tif\"\n",
        "f_rich_2040 <- \"C:/Users/henry.garcia/Desktop/Primates/models_maxent_ALL_ecoregM/0.richness_maps/riqueza_2040_col.tif\"\n",
        "eco_shp     <- \"C:/Users/henry.garcia/Desktop/Primates/ecoregions/wwf_terr_ecos_col.shp\"\n",
        "stopifnot(file.exists(f_rich_2025), file.exists(f_rich_2040), file.exists(eco_shp))\n",
        "\n",
        "# Leer y alinear 2040 a 2025\n",
        "r25    <- rast(f_rich_2025)\n",
        "r40raw <- rast(f_rich_2040)\n",
        "r40    <- if (!compareGeom(r25, r40raw, stopOnError = FALSE)) project(r40raw, r25, method = \"bilinear\") else r40raw\n",
        "\n",
        "# Ecorregiones al CRS de r25 + ID y rasterización\n",
        "eco_sf <- st_read(eco_shp, quiet = TRUE) |> st_make_valid() |> st_transform(st_crs(crs(r25, proj = TRUE)))\n",
        "stopifnot(\"ECO_NAME\" %in% names(eco_sf))\n",
        "eco_sf <- eco_sf |> mutate(ECO_ID = as.integer(factor(ECO_NAME)))\n",
        "eco_v  <- vect(eco_sf)\n",
        "eco_r  <- rasterize(eco_v, r25, field = \"ECO_ID\", touches = TRUE)\n",
        "\n",
        "# Zonal (medias y nº celdas válidas)\n",
        "z_mean_25 <- zonal(r25, eco_r, fun = \"mean\", na.rm = TRUE) |> as.data.frame()\n",
        "z_mean_40 <- zonal(r40, eco_r, fun = \"mean\", na.rm = TRUE) |> as.data.frame()\n",
        "z_n_25    <- zonal(!is.na(r25), eco_r, fun = \"sum\",  na.rm = TRUE) |> as.data.frame()\n",
        "z_n_40    <- zonal(!is.na(r40), eco_r, fun = \"sum\",  na.rm = TRUE) |> as.data.frame()\n",
        "\n",
        "names(z_mean_25) <- c(\"ECO_ID\",\"mean_2025\")\n",
        "names(z_mean_40) <- c(\"ECO_ID\",\"mean_2040\")\n",
        "names(z_n_25)    <- c(\"ECO_ID\",\"n25\")\n",
        "names(z_n_40)    <- c(\"ECO_ID\",\"n40\")\n",
        "\n",
        "eco_names <- eco_sf |> st_drop_geometry() |> select(ECO_ID, ECO_NAME) |> distinct()\n",
        "\n",
        "df <- eco_names %>%\n",
        "  left_join(z_mean_25, by = \"ECO_ID\") %>%\n",
        "  left_join(z_mean_40, by = \"ECO_ID\") %>%\n",
        "  left_join(z_n_25,    by = \"ECO_ID\") %>%\n",
        "  left_join(z_n_40,    by = \"ECO_ID\") %>%\n",
        "  filter((n25 > 0) | (n40 > 0)) %>%\n",
        "  mutate(delta = mean_2040 - mean_2025)\n",
        "\n",
        "# Boxplot comparando promedios por ecorregión\n",
        "df_long <- df |>\n",
        "  pivot_longer(cols = c(mean_2025, mean_2040),\n",
        "               names_to = \"periodo\", values_to = \"riqueza_media\") |>\n",
        "  mutate(periodo = recode(periodo, mean_2025 = \"2025\", mean_2040 = \"2040\"))\n",
        "\n",
        "p_box <- ggplot(df_long, aes(x = periodo, y = riqueza_media, fill = periodo)) +\n",
        "  geom_boxplot(outlier.alpha = 0) +\n",
        "  geom_jitter(width = 0.15, alpha = 0.65, size = 1.6, aes(color = periodo)) +\n",
        "  scale_fill_viridis_d(end = 0.9, guide = \"none\") +\n",
        "  scale_color_viridis_d(end = 0.9, guide = \"none\") +\n",
        "  labs(\n",
        "    title = \"Riqueza promedio por ecorregión (ECO_NAME)\",\n",
        "    subtitle = sprintf(\"n ecorregiones: %d | Promedio global: 2025=%.2f, 2040=%.2f\",\n",
        "                       dplyr::n_distinct(df$ECO_ID),\n",
        "                       mean(df$mean_2025, na.rm = TRUE),\n",
        "                       mean(df$mean_2040, na.rm = TRUE)),\n",
        "    x = NULL, y = \"Riqueza media (promedio por ecorregión)\"\n",
        "  ) +\n",
        "  theme_minimal(base_size = 13) +\n",
        "  theme(panel.grid.minor = element_blank(),\n",
        "        plot.title = element_text(face = \"bold\"),\n",
        "        axis.title.y = element_text(face = \"bold\"))\n",
        "\n",
        "out_png <- \"C:/Users/henry.garcia/Desktop/box_riqueza_promedio_ecoregiones_2025_2040.png\"\n",
        "out_csv <- \"C:/Users/henry.garcia/Desktop/riqueza_promedio_por_ecoregion_2025_2040.csv\"\n",
        "ggsave(out_png, p_box, width = 8.8, height = 6.0, dpi = 300)\n",
        "write_csv(df |> arrange(ECO_NAME), out_csv)\n",
        "message(\"✅ Boxplot: \", out_png)\n",
        "message(\"✅ Tabla (por ecorregión): \", out_csv)\n",
        "\n",
        "# Boxplot del Δ por ecorregión (opcional)\n",
        "p_delta <- ggplot(df, aes(y = delta, x = \"Δ 2040−2025\", fill = \"Δ 2040−2025\")) +\n",
        "  geom_boxplot(outlier.alpha = 0) +\n",
        "  geom_jitter(width = 0.12, alpha = 0.65, size = 1.6, color = \"grey20\") +\n",
        "  scale_fill_viridis_d(end = 0.9, guide = \"none\") +\n",
        "  labs(title = \"Cambio en riqueza promedio por ecorregión (2040−2025)\",\n",
        "       x = NULL, y = \"Δ riqueza (promedio por ecorregión)\") +\n",
        "  theme_minimal(base_size = 13) +\n",
        "  theme(panel.grid.minor = element_blank(),\n",
        "        plot.title = element_text(face = \"bold\"),\n",
        "        axis.title.y = element_text(face = \"bold\"))\n",
        "out_png_delta <- \"C:/Users/henry.garcia/Desktop/box_delta_riqueza_promedio_ecoregiones.png\"\n",
        "ggsave(out_png_delta, p_delta, width = 6.2, height = 6.0, dpi = 300)\n",
        "message(\"✅ Box Δ: \", out_png_delta)\n",
        "\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# D) PRUEBAS PAREADAS POR ECORREGIÓN: 2025 vs 2040 (RIQUEZA)\n",
        "#    - t pareada sobre Δ si normalidad no se rechaza;\n",
        "#      si no, Wilcoxon; si muchos empates, Sign test\n",
        "#    - Exporta resumen global y por ecorregión\n",
        "# ============================================================\n",
        "\n",
        "suppressPackageStartupMessages({\n",
        "  library(dplyr); library(data.table)\n",
        "})\n",
        "\n",
        "# Verificar insumo 'df' (proveniente del bloque C)\n",
        "if (!exists(\"df\")) stop(\"No existe el objeto 'df'. Ejecuta primero el bloque C (zonal y tabla 'df').\")\n",
        "\n",
        "dd <- df %>%\n",
        "  dplyr::filter(!is.na(mean_2025), !is.na(mean_2040)) %>%\n",
        "  dplyr::mutate(delta = mean_2040 - mean_2025)\n",
        "if (nrow(dd) < 3) stop(\"Muy pocas ecorregiones con datos en ambos años para prueba pareada.\")\n",
        "\n",
        "# Normalidad orientativa de Δ (global, solo reportada)\n",
        "sw <- tryCatch(shapiro.test(dd$delta), error = function(e) NULL)\n",
        "tt <- t.test(dd$mean_2040, dd$mean_2025, paired = TRUE, alternative = \"two.sided\")\n",
        "dz <- mean(dd$delta, na.rm = TRUE) / stats::sd(dd$delta, na.rm = TRUE)\n",
        "wx <- suppressWarnings(\n",
        "  wilcox.test(dd$mean_2040, dd$mean_2025,\n",
        "              paired = TRUE, exact = FALSE,\n",
        "              conf.int = TRUE, conf.level = 0.95)\n",
        ")\n",
        "\n",
        "summary_df <- data.frame(\n",
        "  n_ecoregiones = nrow(dd),\n",
        "  media_2025 = mean(dd$mean_2025, na.rm = TRUE),\n",
        "  media_2040 = mean(dd$mean_2040, na.rm = TRUE),\n",
        "  delta_media = mean(dd$delta, na.rm = TRUE),\n",
        "  delta_sd = sd(dd$delta, na.rm = TRUE),\n",
        "  t_stat = unname(tt$statistic),\n",
        "  gl = unname(tt$parameter),\n",
        "  p_t = tt$p.value,\n",
        "  ci_delta_low = tt$conf.int[1],\n",
        "  ci_delta_high = tt$conf.int[2],\n",
        "  cohen_dz = dz,\n",
        "  W_wilcoxon = unname(wx$statistic),\n",
        "  p_wilcoxon = wx$p.value,\n",
        "  wilcox_ci_low = if (!is.null(wx$conf.int)) wx$conf.int[1] else NA_real_,\n",
        "  wilcox_ci_high = if (!is.null(wx$conf.int)) wx$conf.int[2] else NA_real_\n",
        ")\n",
        "\n",
        "out_sum <- \"C:/Users/henry.garcia/Desktop/paired_test_riqueza_summary.csv\"\n",
        "out_per <- \"C:/Users/henry.garcia/Desktop/paired_test_riqueza_por_ecoregion.csv\"\n",
        "utils::write.csv(summary_df, out_sum, row.names = FALSE, fileEncoding = \"UTF-8\")\n",
        "utils::write.csv(dd[, c(\"ECO_NAME\",\"mean_2025\",\"mean_2040\",\"delta\")],\n",
        "                 out_per, row.names = FALSE, fileEncoding = \"UTF-8\")\n",
        "\n",
        "cat(\"============================================================\\n\")\n",
        "cat(sprintf(\"Ecorregiones incluidas: %d\\n\", nrow(dd)))\n",
        "if (!is.null(sw)) {\n",
        "  cat(sprintf(\"Shapiro–Wilk (Δ): W=%.3f, p=%.4g -> %s\\n\",\n",
        "              sw$statistic, sw$p.value,\n",
        "              if (sw$p.value >= 0.05) \"normalidad no rechazada (t pareada OK)\"\n",
        "              else \"normalidad rechazada (reportar también Wilcoxon)\"))\n",
        "}\n",
        "cat(sprintf(\"t pareada: t=%.3f (gl=%d), p=%.5g\\n\", tt$statistic, as.integer(tt$parameter), tt$p.value))\n",
        "cat(sprintf(\"Δ media = %.3f (IC95%%: %.3f a %.3f), Cohen's dz = %.3f\\n\",\n",
        "            mean(dd$delta), tt$conf.int[1], tt$conf.int[2], dz))\n",
        "cat(sprintf(\"Wilcoxon pareada: W=%g, p=%.5g\", wx$statistic, wx$p.value))\n",
        "if (!is.null(wx$conf.int)) cat(sprintf(\", IC mediana Δ [%.3f, %.3f]\\n\", wx$conf.int[1], wx$conf.int[2])) else cat(\"\\n\")\n",
        "cat(\"Archivos:\\n - Resumen: \", out_sum, \"\\n - Por ecorregión: \", out_per, \"\\n\")\n",
        "cat(\"============================================================\\n\")\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# E) POST HOC POR ECORREGIÓN (selección automática de prueba)\n",
        "#    - t(Δ) si normalidad OK; si no, Wilcoxon; con ≥30% empates → Sign test\n",
        "#    - Exporta CSV y gráfico de Δ coloreado por significancia (FDR BH)\n",
        "# ============================================================\n",
        "\n",
        "suppressPackageStartupMessages({\n",
        "  library(ggplot2)\n",
        "})\n",
        "\n",
        "# Reconstruir insumos mínimos si faltan en memoria\n",
        "if (!exists(\"r25\") || !exists(\"r40\")) {\n",
        "  f_rich_2025 <- \"C:/Users/henry.garcia/Desktop/Primates/models_maxent_ALL_ecoregM/0.richness_maps/riqueza_2025_col.tif\"\n",
        "  f_rich_2040 <- \"C:/Users/henry.garcia/Desktop/Primates/models_maxent_ALL_ecoregM/0.richness_maps/riqueza_2040_col.tif\"\n",
        "  stopifnot(file.exists(f_rich_2025), file.exists(f_rich_2040))\n",
        "  r25    <- rast(f_rich_2025)\n",
        "  r40raw <- rast(f_rich_2040)\n",
        "  r40    <- if (!compareGeom(r25, r40raw, stopOnError = FALSE)) project(r40raw, r25, method = \"bilinear\") else r40raw\n",
        "}\n",
        "if (!exists(\"eco_r\") || !exists(\"eco_sf\")) {\n",
        "  eco_shp <- \"C:/Users/henry.garcia/Desktop/Primates/ecoregions/wwf_terr_ecos_col.shp\"\n",
        "  stopifnot(file.exists(eco_shp))\n",
        "  eco_sf <- st_read(eco_shp, quiet = TRUE) |> st_make_valid() |>\n",
        "    st_transform(st_crs(crs(r25, proj = TRUE)))\n",
        "  stopifnot(\"ECO_NAME\" %in% names(eco_sf))\n",
        "  eco_sf <- eco_sf |> mutate(ECO_ID = as.integer(factor(ECO_NAME)))\n",
        "  eco_r  <- rasterize(vect(eco_sf), r25, field = \"ECO_ID\", touches = TRUE)\n",
        "}\n",
        "\n",
        "# Extraer pares por píxel y ecorregión\n",
        "v25 <- values(r25, mat = FALSE)\n",
        "v40 <- values(r40, mat = FALSE)\n",
        "zid <- values(eco_r, mat = FALSE)\n",
        "ok  <- !is.na(zid) & !is.na(v25) & !is.na(v40)\n",
        "DT  <- data.table(ECO_ID = zid[ok], v25 = v25[ok], v40 = v40[ok], delta = v40[ok] - v25[ok])\n",
        "\n",
        "# Utilidades de prueba\n",
        "shapiro_smart <- function(x) {\n",
        "  x <- x[is.finite(x)]\n",
        "  n <- length(x)\n",
        "  if (n < 3) return(list(p.value = NA_real_, W = NA_real_))\n",
        "  if (n > 5000) x <- sample(x, 5000)\n",
        "  tryCatch(shapiro.test(x), error = function(e) list(p.value = NA_real_, W = NA_real_))\n",
        "}\n",
        "sign_test <- function(d) {\n",
        "  d <- d[is.finite(d)]\n",
        "  nz <- d[d != 0]\n",
        "  n  <- length(nz)\n",
        "  if (n == 0) return(list(p.value = 1, stat = 0, n = 0))\n",
        "  kpos <- sum(nz > 0)\n",
        "  bt   <- binom.test(kpos, n, p = 0.5, alternative = \"two.sided\")\n",
        "  list(p.value = bt$p.value, stat = kpos, n = n)\n",
        "}\n",
        "\n",
        "# Analítica por ecorregión (selección de prueba)\n",
        "analyze_zone <- function(df_zone) {\n",
        "  n <- nrow(df_zone)\n",
        "  mean25 <- as.numeric(mean(df_zone$v25, na.rm = TRUE))\n",
        "  mean40 <- as.numeric(mean(df_zone$v40, na.rm = TRUE))\n",
        "  d <- df_zone$delta\n",
        "  delta_mean <- as.numeric(mean(d, na.rm = TRUE))\n",
        "  if (n < 10) {\n",
        "    return(data.frame(test = \"NA\", n = as.integer(n), mean25 = mean25, mean40 = mean40,\n",
        "                      delta_mean = delta_mean, stat = NA_real_, p = NA_real_,\n",
        "                      method_note = \"n<10\", stringsAsFactors = FALSE))\n",
        "  }\n",
        "  prop_ties <- mean(d == 0, na.rm = TRUE)\n",
        "  if (prop_ties >= 0.30) {\n",
        "    nz <- d[d != 0]\n",
        "    if (length(nz) == 0) {\n",
        "      return(data.frame(test = \"Sign (binomial)\", n = as.integer(n), mean25 = mean25, mean40 = mean40,\n",
        "                        delta_mean = delta_mean, stat = 0, p = 1,\n",
        "                        method_note = sprintf(\"ties=%.1f%%; sin datos no nulos\", 100*prop_ties),\n",
        "                        stringsAsFactors = FALSE))\n",
        "    }\n",
        "    kpos <- sum(nz > 0)\n",
        "    bt <- binom.test(kpos, length(nz), p = 0.5, alternative = \"two.sided\")\n",
        "    return(data.frame(test = \"Sign (binomial)\", n = as.integer(n), mean25 = mean25, mean40 = mean40,\n",
        "                      delta_mean = delta_mean, stat = as.numeric(kpos), p = as.numeric(bt$p.value),\n",
        "                      method_note = sprintf(\"ties=%.1f%%\", 100*prop_ties), stringsAsFactors = FALSE))\n",
        "  }\n",
        "  sw <- shapiro_smart(d)\n",
        "  if (!is.na(sw$p.value) && sw$p.value >= 0.05) {\n",
        "    tt <- t.test(d, mu = 0)\n",
        "    sd_d <- sd(d, na.rm = TRUE)\n",
        "    dz <- if (is.finite(sd_d) && sd_d > 0) mean(d, na.rm = TRUE)/sd_d else NA_real_\n",
        "    data.frame(test = \"t pareada (Δ)\", n = as.integer(n), mean25 = mean25, mean40 = mean40,\n",
        "               delta_mean = delta_mean, stat = as.numeric(tt$statistic), p = as.numeric(tt$p.value),\n",
        "               method_note = sprintf(\"Shapiro p=%.3g; dz=%.3f\", sw$p.value, dz), stringsAsFactors = FALSE)\n",
        "  } else {\n",
        "    wx <- suppressWarnings(wilcox.test(df_zone$v40, df_zone$v25, paired = TRUE, exact = FALSE))\n",
        "    data.frame(test = \"Wilcoxon pareada\", n = as.integer(n), mean25 = mean25, mean40 = mean40,\n",
        "               delta_mean = delta_mean, stat = as.numeric(wx$statistic), p = as.numeric(wx$p.value),\n",
        "               method_note = if (is.na(sw$p.value)) \"Shapiro NA\" else sprintf(\"Shapiro p=%.3g\", sw$p.value),\n",
        "               stringsAsFactors = FALSE)\n",
        "  }\n",
        "}\n",
        "\n",
        "# Ejecutar por ecorregión\n",
        "res_list <- lapply(split(DT, DT$ECO_ID), analyze_zone)\n",
        "RES <- data.table::rbindlist(res_list, idcol = \"ECO_ID\", use.names = TRUE, fill = TRUE)\n",
        "RES[, ECO_ID := as.integer(ECO_ID)]\n",
        "\n",
        "# Añadir nombres de ecorregión\n",
        "if (exists(\"eco_sf\")) {\n",
        "  name_map <- sf::st_drop_geometry(eco_sf)[, c(\"ECO_ID\",\"ECO_NAME\")] |> dplyr::distinct()\n",
        "  RES <- merge(RES, data.table::as.data.table(name_map), by = \"ECO_ID\", all.x = TRUE)\n",
        "} else {\n",
        "  RES[, ECO_NAME := paste0(\"ECO_\", ECO_ID)]\n",
        "}\n",
        "\n",
        "# Ajuste FDR (BH), ordenar y exportar\n",
        "RES <- RES[order(p)]\n",
        "RES[, p_adj_BH := p.adjust(p, method = \"BH\")]\n",
        "RES[, decision := ifelse(!is.na(p_adj_BH) & p_adj_BH < 0.05, \"Significativo (FDR<0.05)\", \"ns\")]\n",
        "\n",
        "out_csv <- \"C:/Users/henry.garcia/Desktop/posthoc_pareado_por_ecoregion.csv\"\n",
        "data.table::fwrite(RES[, .(ECO_ID, ECO_NAME, n, mean25, mean40, delta_mean,\n",
        "                           test, stat, p, p_adj_BH, decision, method_note)],\n",
        "                   out_csv)\n",
        "message(\"✅ Resultados por ecorregión guardados en: \", out_csv)\n",
        "\n",
        "# Gráfico Δ por ecorregión coloreado por significancia\n",
        "p_sig <- ggplot(RES, aes(x = reorder(ECO_NAME, delta_mean), y = delta_mean, fill = decision)) +\n",
        "  geom_col() +\n",
        "  coord_flip() +\n",
        "  scale_fill_manual(values = c(\"Significativo (FDR<0.05)\" = \"#21918c\", \"ns\" = \"grey80\")) +\n",
        "  labs(title = \"Δ riqueza (2040−2025) por ecorregión\",\n",
        "       x = NULL, y = \"Δ riqueza promedio\", fill = NULL) +\n",
        "  theme_minimal(base_size = 12) +\n",
        "  theme(plot.title = element_text(face = \"bold\"))\n",
        "ggsave(\"C:/Users/henry.garcia/Desktop/posthoc_delta_bar_sig.png\", p_sig, width = 9, height = 10, dpi = 300)\n",
        "message(\"✅ Gráfico Δ por ecorregión: C:/Users/henry.garcia/Desktop/posthoc_delta_bar_sig.png\")\n",
        "\n",
        "\n",
        "\n",
        "# ============================================================\n",
        "# F) RIESGO DE DEFORESTACIÓN (90 m)\n",
        "#    - Mapa de probabilidad (colores V-A-R) en bosque 2023\n",
        "#    - Probabilidad acumulada P = 1 - (1 - p)^n y forest01_2040 (umbral 0.45)\n",
        "#    - Áreas de bosque (ha) por ecorregión: 2023 vs 2040 + barras\n",
        "# ============================================================\n",
        "\n",
        "pkgs <- c(\"terra\",\"sf\",\"ggplot2\",\"tidyterra\",\"data.table\",\"dplyr\",\"tidyr\")\n",
        "new  <- setdiff(pkgs, rownames(installed.packages()))\n",
        "if (length(new)) install.packages(new, dependencies = TRUE)\n",
        "library(terra); library(sf); library(ggplot2); library(tidyterra)\n",
        "library(data.table); library(dplyr); library(tidyr)\n",
        "\n",
        "# Rutas\n",
        "risk_path  <- \"C:/Users/henry.garcia/Desktop/Primates/outputs/defrisk_prob_2025_2030_forestOnly_90m.tif\"\n",
        "f2023_path <- \"C:/Users/henry.garcia/Desktop/Primates/predictors/DefRisk/rasters/forest01/forest01_2023_90m.tif\"\n",
        "eco_shp    <- \"C:/Users/henry.garcia/Desktop/Primates/ecoregions/wwf_terr_ecos_col.shp\"\n",
        "stopifnot(file.exists(risk_path), file.exists(f2023_path), file.exists(eco_shp))\n",
        "\n",
        "# Leer y alinear riesgo a malla 2023 si hace falta\n",
        "risk  <- rast(risk_path)   # p en [0,1] sobre bosque; fuera = NA\n",
        "f2023 <- rast(f2023_path)  # 1=bosque, 0=no bosque\n",
        "if (!compareGeom(f2023, risk, stopOnError = FALSE)) {\n",
        "  risk <- project(risk, f2023, method = \"bilinear\")\n",
        "}\n",
        "\n",
        "# Ecorregiones (contorno y raster para zonal)\n",
        "eco_sf0 <- st_read(eco_shp, quiet = TRUE) |> st_make_valid()\n",
        "eco_sf  <- suppressWarnings(st_transform(eco_sf0, st_crs(crs(f2023, proj = TRUE))))\n",
        "stopifnot(\"ECO_NAME\" %in% names(eco_sf))\n",
        "eco_sf <- eco_sf |> mutate(ECO_ID = as.integer(factor(ECO_NAME)))\n",
        "eco_r  <- rasterize(vect(eco_sf), f2023, field = \"ECO_ID\", touches = TRUE)\n",
        "\n",
        "# (1) Mapa de riesgo (verde→amarillo→rojo) solo en bosque\n",
        "risk_plot <- terra::mask(risk, f2023, maskvalue = 0)\n",
        "p_risk <- ggplot() +\n",
        "  geom_spatraster(data = risk_plot, na.rm = TRUE) +\n",
        "  scale_fill_gradientn(\n",
        "    name   = \"Prob. deforestación\\n(2025–2030)\",\n",
        "    colours = c(\"#2CA02C\", \"#FFFF00\", \"#D62728\"),\n",
        "    values  = scales::rescale(c(0, 0.5, 1)),\n",
        "    limits  = c(0, 1),\n",
        "    oob     = scales::squish,\n",
        "    na.value = NA\n",
        "  ) +\n",
        "  geom_sf(data = eco_sf, fill = NA, color = \"black\", linewidth = 0.25) +\n",
        "  coord_sf(expand = FALSE, datum = NA) +\n",
        "  theme_void(base_size = 11) +\n",
        "  theme(plot.title = element_text(face = \"bold\"),\n",
        "        panel.background = element_rect(fill = \"white\", colour = NA),\n",
        "        plot.background  = element_rect(fill = \"white\", colour = NA)) +\n",
        "  labs(title = \"Riesgo de deforestación (90 m) — V-A-R\")\n",
        "ggsave(\"C:/Users/henry.garcia/Desktop/map_defrisk_VYR.png\", p_risk, width = 9, height = 7, dpi = 300)\n",
        "\n",
        "# (2) Probabilidad acumulada y forest01_2040 con umbral 0.45\n",
        "n_steps <- 3\n",
        "p <- risk\n",
        "p <- terra::ifel(p < 0, 0, p)\n",
        "p <- terra::ifel(p > 1, 1, p)\n",
        "p_cum <- 1 - (1 - p)^n_steps\n",
        "thr   <- 0.45\n",
        "lost        <- p_cum >= thr\n",
        "forest2040  <- ifel(f2023 == 1 & lost, 0, f2023)  # 1=bosque, 0=no bosque\n",
        "if (all(is.na(values(forest2040)))) warning(\"forest2040 resultó todo NA; revisa insumos/umbral.\")\n",
        "writeRaster(forest2040, \"C:/Users/henry.garcia/Desktop/forest01_2040_90m.tif\", overwrite = TRUE)\n",
        "\n",
        "# (3) Máscaras de bosque (0 -> NA) para cálculo de área\n",
        "f2023_mask <- ifel(f2023 == 1, 1, NA)\n",
        "f2040_mask <- ifel(forest2040 == 1, 1, NA)\n",
        "\n",
        "# (4) Área de BOSQUE por ecorregión (ha) 2023 vs 2040\n",
        "px_ha <- (90 * 90) / 10000  # 0.81 ha por píxel\n",
        "z_2023 <- zonal(f2023_mask, eco_r, fun = \"sum\", na.rm = TRUE) |> as.data.frame()\n",
        "z_2040 <- zonal(f2040_mask, eco_r, fun = \"sum\", na.rm = TRUE) |> as.data.frame()\n",
        "names(z_2023) <- c(\"ECO_ID\",\"n_pix_bosque_2023\")\n",
        "names(z_2040) <- c(\"ECO_ID\",\"n_pix_bosque_2040\")\n",
        "\n",
        "areas <- dplyr::full_join(z_2023, z_2040, by = \"ECO_ID\") |>\n",
        "  dplyr::mutate(across(starts_with(\"n_pix_bosque_\"), ~ tidyr::replace_na(., 0))) |>\n",
        "  dplyr::mutate(area_ha_bosque_2023 = n_pix_bosque_2023 * px_ha,\n",
        "                area_ha_bosque_2040 = n_pix_bosque_2040 * px_ha,\n",
        "                delta_ha = area_ha_bosque_2040 - area_ha_bosque_2023) |>\n",
        "  dplyr::left_join(st_drop_geometry(eco_sf)[, c(\"ECO_ID\",\"ECO_NAME\")] |> dplyr::distinct(), by = \"ECO_ID\") |>\n",
        "  dplyr::relocate(ECO_ID, ECO_NAME)\n",
        "\n",
        "# Guardar tabla y barras\n",
        "out_csv <- \"C:/Users/henry.garcia/Desktop/area_bosque_por_ecoregion_2023_2040.csv\"\n",
        "data.table::fwrite(areas, out_csv)\n",
        "\n",
        "areas_long <- areas |>\n",
        "  dplyr::select(ECO_NAME, area_ha_bosque_2023, area_ha_bosque_2040) |>\n",
        "  tidyr::pivot_longer(cols = starts_with(\"area_ha_bosque_\"),\n",
        "                      names_to = \"periodo\", values_to = \"area_ha\") |>\n",
        "  dplyr::mutate(periodo = dplyr::recode(periodo,\n",
        "                                        area_ha_bosque_2023 = \"2023\",\n",
        "                                        area_ha_bosque_2040 = \"2040\"))\n",
        "ord <- areas |> dplyr::arrange(dplyr::desc(area_ha_bosque_2040)) |> dplyr::pull(ECO_NAME)\n",
        "areas_long$ECO_NAME <- factor(areas_long$ECO_NAME, levels = ord)\n",
        "\n",
        "p_bosque <- ggplot(areas_long, aes(x = ECO_NAME, y = area_ha, fill = periodo)) +\n",
        "  geom_col(position = position_dodge(width = 0.7), width = 0.7) +\n",
        "  scale_fill_viridis_d(end = 0.9, name = NULL) +\n",
        "  labs(title = \"Área de BOSQUE por ecorregión (90 m)\",\n",
        "       subtitle = sprintf(\"Prob. acumulada con n=%d; umbral P≥%.2f para pérdida\", n_steps, thr),\n",
        "       x = NULL, y = \"Área de bosque (ha)\") +\n",
        "  coord_flip() +\n",
        "  theme_minimal(base_size = 12) +\n",
        "  theme(plot.title = element_text(face = \"bold\"),\n",
        "        panel.grid.minor = element_blank())\n",
        "\n",
        "ggsave(\"C:/Users/henry.garcia/Desktop/barras_area_bosque_ecoregion_2023_2040.png\",\n",
        "       p_bosque, width = 12, height = max(6, 0.35*length(ord)+2), dpi = 300)\n",
        "\n",
        "message(\"✅ Mapa riesgo: C:/Users/henry.garcia/Desktop/map_defrisk_VYR.png\")\n",
        "message(\"✅ forest01_2040 (1=bosque): C:/Users/henry.garcia/Desktop/forest01_2040_90m.tif\")\n",
        "message(\"✅ Tabla áreas (ha): \", out_csv)\n",
        "message(\"✅ Barras área bosque: C:/Users/henry.garcia/Desktop/barras_area_bosque_ecoregion_2023_2040.png\")\n"
      ]
    }
  ]
}